// AUTO-GENERATED by scripts/build-quizzes.ts. Do not edit by hand.
export interface QuizQuestion {
  id: string;
  prompt: string;
  options: string[];
  answerIndex: number;
  explanation: string;
}
export interface PillarQuiz {
  pillarN: number;
  questions: QuizQuestion[];
}

export const QUIZZES: PillarQuiz[] = [
 {
  "pillarN": 1,
  "questions": [
   {
    "id": "p1-q1",
    "prompt": "Which Pillar 1 subtopic carries the [KEY] marker and is covered by 3B1B Chapter 6?",
    "options": [
     "Softmax and output sampling",
     "Attention: Q/K/V, masking, multi-head",
     "Tokenization with BPE",
     "Backpropagation basics"
    ],
    "answerIndex": 1,
    "explanation": "Attention: Q/K/V, masking, multi-head is marked [KEY]; taught in Ch.6 Attention, step-by-step - 3B1B."
   },
   {
    "id": "p1-q2",
    "prompt": "Per the Pillar 1 gap-fill callout, why must positional encoding be injected into transformer inputs?",
    "options": [
     "To normalize softmax outputs",
     "Because token order matters and attention alone does not encode position",
     "To shrink the embedding matrix",
     "To compress the vocabulary"
    ],
    "answerIndex": 1,
    "explanation": "Gap fill: positional encoding injects order; learn it via Karpathy's Let's build GPT from scratch."
   },
   {
    "id": "p1-q3",
    "prompt": "Which often-skipped topic does the roadmap highlight about where an LLM stores factual knowledge?",
    "options": [
     "Facts live in MLP/feed-forward layers",
     "Facts live only in attention heads",
     "Facts are stored in the tokenizer",
     "Facts sit in the final softmax layer"
    ],
    "answerIndex": 0,
    "explanation": "Gap fill says MLP/feed-forward layers store factual knowledge; see Ch.7 How might LLMs store facts - 3B1B."
   },
   {
    "id": "p1-q4",
    "prompt": "According to the gap-fill warning, learners who watch only the attention video miss which two topics?",
    "options": [
     "Softmax and sampling strategies",
     "Positional encoding and fact storage in MLP layers",
     "Tokenization and backpropagation",
     "Multi-head attention and masking"
    ],
    "answerIndex": 1,
    "explanation": "Gap fill: most watch only attention; add positional encoding (Karpathy) and MLP fact storage (3B1B Ch.7)."
   },
   {
    "id": "p1-q5",
    "prompt": "Which chapter covers the full forward pass, embeddings, and softmax?",
    "options": [
     "Ch.5 Transformers, the tech behind LLMs - 3B1B",
     "Ch.6 Attention, step-by-step - 3B1B",
     "Ch.7 How might LLMs store facts - 3B1B",
     "LLMs explained briefly - 3B1B playlist"
    ],
    "answerIndex": 0,
    "explanation": "Ch.5 Transformers, the tech behind LLMs (27m) covers forward pass, embeddings, softmax."
   },
   {
    "id": "p1-q6",
    "prompt": "In the roadmap, Tokenization/BPE plus positional encoding are assigned to which resource?",
    "options": [
     "3B1B Ch.7",
     "Karpathy - Let's build GPT from scratch",
     "Ed Donner LLM Engineering Wk1",
     "Andrew Ng Agentic AI course"
    ],
    "answerIndex": 1,
    "explanation": "Tokenization/BPE and positional encoding map to Karpathy's Let's build GPT from scratch (1h56m)."
   },
   {
    "id": "p1-q7",
    "prompt": "What does the roadmap advise regarding 3B1B Chapters 1-4?",
    "options": [
     "Watch them twice before Chapter 5",
     "Skip unless you want neural-net basics/backprop; not needed to build",
     "They are mandatory prerequisites for attention",
     "They replace Karpathy's video entirely"
    ],
    "answerIndex": 1,
    "explanation": "Gap fill: skip 3B1B Ch.1-4 (neural-net basics/backprop) unless wanted - not needed to build."
   },
   {
    "id": "p1-q8",
    "prompt": "Which resource does the roadmap assign to the big-picture subtopic of what an LLM is?",
    "options": [
     "LLMs explained briefly - 3B1B playlist (8m)",
     "Karpathy - Let's build GPT from scratch",
     "3B1B Ch.5 Transformers",
     "PEFT Explained - Arivu"
    ],
    "answerIndex": 0,
    "explanation": "Big-picture subtopic maps to LLMs explained briefly, the 8-minute 3Blue1Brown playlist."
   }
  ]
 },
 {
  "pillarN": 2,
  "questions": [
   {
    "id": "p2-q1",
    "prompt": "How does the roadmap phrase the goal of Pillar 2, LLM App Fundamentals?",
    "options": [
     "From calling an API to shipping an LLM feature",
     "From prompt engineering to model training",
     "From Python basics to GPU clusters",
     "From chatbots to distributed systems"
    ],
    "answerIndex": 0,
    "explanation": "Pillar 2 goal: go from calling an API to shipping an LLM feature, via Ed Donner's LLM Engineering course."
   },
   {
    "id": "p2-q2",
    "prompt": "Why does an app use tool/function calling?",
    "options": [
     "To reduce token costs automatically",
     "To let the model request external function calls so it can act on real data and systems",
     "To compress the context window",
     "To fine-tune on new data mid-conversation"
    ],
    "answerIndex": 1,
    "explanation": "Tool/function calling lets a model invoke external functions; covered in Ed Donner Wk2 plus a ReAct explainer."
   },
   {
    "id": "p2-q3",
    "prompt": "Which library does the roadmap name for building fast UIs in Pillar 2?",
    "options": [
     "Streamlit",
     "React",
     "Gradio",
     "Pydantic"
    ],
    "answerIndex": 2,
    "explanation": "Fast UIs subtopic names Gradio, taught in Ed Donner LLM Engineering Wk2."
   },
   {
    "id": "p2-q4",
    "prompt": "Which week of Ed Donner's course covers open-source models and HuggingFace?",
    "options": [
     "Wk2",
     "Wk3",
     "Wk4",
     "Wks 1-2"
    ],
    "answerIndex": 1,
    "explanation": "Open-source models and HuggingFace are scheduled in Ed Donner LLM Engineering Wk3."
   },
   {
    "id": "p2-q5",
    "prompt": "Per the roadmap, how should model selection be done in Wk4?",
    "options": [
     "Random provider sampling",
     "Using leaderboards",
     "Always pick largest parameter count",
     "Pick whichever is cheapest"
    ],
    "answerIndex": 1,
    "explanation": "Model selection / leaderboards is the Wk4 topic in Ed Donner LLM Engineering."
   },
   {
    "id": "p2-q6",
    "prompt": "Structured output in Pillar 2 relies on which formats and resource?",
    "options": [
     "YAML via Anthropic docs",
     "CSV via pandas docs",
     "JSON/Pydantic via OpenAI docs",
     "XML via LangChain docs"
    ],
    "answerIndex": 2,
    "explanation": "Structured output means JSON with Pydantic; see Structured outputs - OpenAI docs."
   },
   {
    "id": "p2-q7",
    "prompt": "What does the roadmap say makes Ed Donner's course well suited for this pillar?",
    "options": [
     "It requires cloud GPUs only",
     "It is Ollama-first and laptop-friendly",
     "It focuses exclusively on vision models",
     "It avoids APIs entirely"
    ],
    "answerIndex": 1,
    "explanation": "Pillar 2 intro: Ed Donner's course is strongest here because it is Ollama-first and laptop-friendly."
   },
   {
    "id": "p2-q8",
    "prompt": "Which topics fall under Ed Donner Wks 1-2 per the roadmap?",
    "options": [
     "Fine-tuning and LoRA ranks",
     "APIs, prompts, streaming, multi-provider",
     "MCP servers and auth",
     "RAGAS evaluation harnesses"
    ],
    "answerIndex": 1,
    "explanation": "Wks 1-2 cover APIs, prompts, streaming, multi-provider; Ed Donner LLM Engineering (repo)."
   }
  ]
 },
 {
  "pillarN": 3,
  "questions": [
   {
    "id": "p3-q1",
    "prompt": "Which Pillar 3 foundations subtopic carries the [KEY] marker?",
    "options": [
     "Chunking strategies",
     "Why RAG; embeddings; vector DB; cosine similarity",
     "Query transforms",
     "GraphRAG summaries"
    ],
    "answerIndex": 1,
    "explanation": "Foundations [KEY]: why RAG, embeddings, vector DB, cosine similarity; RAG from First Principles - Ankit Bansal (38m)."
   },
   {
    "id": "p3-q2",
    "prompt": "What components make up hybrid retrieval as described in the roadmap?",
    "options": [
     "BM25 keyword search plus dense embeddings, fused using reciprocal rank fusion (RRF)",
     "Dense vectors only",
     "Cross-encoder scoring over every chunk",
     "Graph traversal plus RAPTOR trees"
    ],
    "answerIndex": 0,
    "explanation": "Hybrid search = BM25 + dense + RRF; see Production RAG w/ LangChain and Vector DBs - freeCodeCamp (7h38m)."
   },
   {
    "id": "p3-q3",
    "prompt": "Which techniques does the roadmap list under reranking?",
    "options": [
     "BM25 and TF-IDF",
     "HyDE and multi-query expansion",
     "Cross-encoders and ColBERT",
     "Parent-child chunk merging"
    ],
    "answerIndex": 2,
    "explanation": "Reranking uses cross-encoders or ColBERT; see Advanced RAG techniques - Field Guide to AI (9m read)."
   },
   {
    "id": "p3-q4",
    "prompt": "HyDE and multi-query belong to which category of advanced RAG techniques?",
    "options": [
     "Reranking",
     "Chunking",
     "Evaluation metrics",
     "Query transforms"
    ],
    "answerIndex": 3,
    "explanation": "HyDE and multi-query are query transforms; see Advanced RAG: hybrid, reranking, query expansion."
   },
   {
    "id": "p3-q5",
    "prompt": "Which chunking strategies does the roadmap name as advanced alternatives?",
    "options": [
     "Parent-child and sentence-window",
     "Random shuffling",
     "Token deduplication",
     "Sliding softmax windows"
    ],
    "answerIndex": 0,
    "explanation": "Advanced chunking = parent-child and sentence-window; see 12 Advanced RAG Techniques (2026) - Atlan."
   },
   {
    "id": "p3-q6",
    "prompt": "Per the roadmap rule of thumb, which RAGAS metrics measure retrieval quality rather than generation quality?",
    "options": [
     "Faithfulness and answer relevancy",
     "Context precision and context recall",
     "BLEU and ROUGE",
     "Latency and cost"
    ],
    "answerIndex": 1,
    "explanation": "Measure retrieval via context precision/recall separately from generation faithfulness; RAGAS explained - Logical Lenses."
   },
   {
    "id": "p3-q7",
    "prompt": "Per the gap-fill callout, how much does hybrid search plus reranking lift factual accuracy over basic embed-and-top-k RAG?",
    "options": [
     "From 44% toward about 63% on the CRAG benchmark",
     "From 10% to 20% on SQuAD",
     "From 80% to 99% on MMLU",
     "No measurable change"
    ],
    "answerIndex": 0,
    "explanation": "Gap fill cites CRAG benchmark: basic RAG scores roughly 44%; hybrid search plus reranking pushes toward 63%."
   },
   {
    "id": "p3-q8",
    "prompt": "The roadmap says do NOT ship RAG without three things. Which set is correct?",
    "options": [
     "A larger model, longer prompts, more tokens",
     "A reranker, hybrid BM25+dense retrieval, and a RAGAS eval harness run in CI on every change",
     "Fine-tuning, quantization, distillation",
     "GraphRAG, RAPTOR, contextual retrieval"
    ],
    "answerIndex": 1,
    "explanation": "Gap fill ship checklist: reranker, hybrid (BM25+dense) retrieval, RAGAS eval harness in CI on every change."
   }
  ]
 },
 {
  "pillarN": 4,
  "questions": [
   {
    "id": "p4-q1",
    "prompt": "What is the one rule of fine-tuning marked [KEY] in Pillar 4?",
    "options": [
     "Fine-tuning teaches knowledge, not behavior",
     "Fine-tuning teaches behavior, not knowledge",
     "Fine-tuning always beats RAG",
     "Fine-tuning requires full-parameter retraining"
    ],
    "answerIndex": 1,
    "explanation": "[KEY] rule from How to Fine-Tune an LLM (2026): fine-tune equals behavior, not knowledge."
   },
   {
    "id": "p4-q2",
    "prompt": "For fresh or frequently changing facts that need citations, which approach does the gap-fill callout recommend?",
    "options": [
     "Full fine-tuning",
     "QLoRA adapters",
     "RAG",
     "Longer system prompts"
    ],
    "answerIndex": 2,
    "explanation": "Gap fill: RAG for fresh/changing facts and citations; never fine-tune to teach your documents."
   },
   {
    "id": "p4-q3",
    "prompt": "According to the roadmap, fine-tuning is the right tool for which goals?",
    "options": [
     "Injecting up-to-date facts",
     "Format, tone, domain vocabulary, and reasoning style",
     "Providing source citations",
     "Replacing a vector database"
    ],
    "answerIndex": 1,
    "explanation": "Gap fill: fine-tune for format, tone, domain vocabulary, reasoning style; facts stay with RAG."
   },
   {
    "id": "p4-q4",
    "prompt": "What anti-pattern does the gap-fill callout explicitly warn against?",
    "options": [
     "Using LoRA rank above 64",
     "Fine-tuning to teach the model your documents",
     "Combining RAG with a reranker",
     "Quantizing a frozen base model"
    ],
    "answerIndex": 1,
    "explanation": "Gap fill: never fine-tune to teach it your documents - that is knowledge, not behavior."
   },
   {
    "id": "p4-q5",
    "prompt": "What does QLoRA specifically involve per the roadmap?",
    "options": [
     "Training every parameter in 16-bit precision",
     "A frozen base quantized to 4-bit NF4 plus small trainable low-rank adapters on attention projections",
     "Distilling into a smaller student model",
     "Pruning weights to sparse matrices"
    ],
    "answerIndex": 1,
    "explanation": "Gap fill: QLoRA = 4-bit NF4 frozen base plus trainable low-rank adapters on attention projections; Mark Hennings - LoRA & QLoRA In-Depth."
   },
   {
    "id": "p4-q6",
    "prompt": "Which LoRA hyperparameters does the roadmap highlight?",
    "options": [
     "Learning rate, batch size, epochs",
     "Rank, alpha, dropout",
     "Temperature, top-p, max tokens",
     "Layers, heads, hidden size"
    ],
    "answerIndex": 1,
    "explanation": "Subtopic lists rank, alpha, dropout, 4-bit NF4; see Mark Hennings - LoRA & QLoRA In-Depth (15m)."
   },
   {
    "id": "p4-q7",
    "prompt": "Which three PEFT methods does the quick overview group together?",
    "options": [
     "LoRA, QLoRA, DoRA",
     "BM25, ColBERT, HyDE",
     "RAGAS, BLEU, ROUGE",
     "ReAct, Reflexion, CoT"
    ],
    "answerIndex": 0,
    "explanation": "Quick PEFT overview covers LoRA, QLoRA, DoRA; see PEFT Explained - Arivu (4m)."
   },
   {
    "id": "p4-q8",
    "prompt": "How does the roadmap characterize fine-tuning's importance for typical app work?",
    "options": [
     "Required for every project",
     "Optional for most app work but a common interview topic",
     "Obsolete now that RAG exists",
     "Only relevant to frontier labs"
    ],
    "answerIndex": 1,
    "explanation": "Pillar 4 goal: know when NOT to fine-tune; optional for most app work yet a common interview topic; practiced in Ed Donner Wks 6-7."
   }
  ]
 },
 {
  "pillarN": 5,
  "questions": [
   {
    "id": "p5-q1",
    "prompt": "Which distinction is marked [KEY] in Jeff Su's AI Agents, Clearly Explained?",
    "options": [
     "Agent vs workflow: agents choose their own steps and tools; workflows follow fixed developer-defined paths",
     "Chatbot vs autocomplete",
     "Supervised vs unsupervised learning",
     "Open-source vs proprietary models"
    ],
    "answerIndex": 0,
    "explanation": "[KEY] subtopic Agent vs workflow plus ReAct loop comes from AI Agents, Clearly Explained - Jeff Su (10m)."
   },
   {
    "id": "p5-q2",
    "prompt": "What is the core loop of the ReAct pattern?",
    "options": [
     "Train, evaluate, deploy repeatedly",
     "Reason about a step, take an action with a tool, observe results, repeat until done",
     "Compress, isolate, summarize",
     "Embed, retrieve, rerank"
    ],
    "answerIndex": 1,
    "explanation": "ReAct interleaves reasoning and acting; see ReAct Agents, clearly explained - Akshay Pachaar (6m)."
   },
   {
    "id": "p5-q3",
    "prompt": "Andrew Ng's Agentic AI course, marked [KEY], covers which four design patterns plus evals?",
    "options": [
     "Reflection, tool use, planning, multi-agent",
     "RAG, caching, routing, batching",
     "LoRA, QLoRA, DoRA, PEFT",
     "BM25, RRF, HyDE, RAPTOR"
    ],
    "answerIndex": 0,
    "explanation": "Agentic AI - Andrew Ng, DeepLearning.AI (7h45m) [KEY] teaches reflection, tool use, planning, multi-agent patterns plus evals."
   },
   {
    "id": "p5-q4",
    "prompt": "Per the roadmap's module mapping, which module covers which pattern?",
    "options": [
     "Module 1 Planning, Module 2 Reflection, Module 3 Tool use, Module 5 Multi-agent",
     "Module 1 Multi-agent, Module 2 Planning, Module 3 Reflection, Module 5 Tool use",
     "Module 1 Tool use, Module 2 Multi-agent, Module 3 Planning, Module 5 Reflection",
     "All four patterns appear in Module 1 only"
    ],
    "answerIndex": 0,
    "explanation": "Roadmap maps Reflection/Tool use/Planning/Multi-agent to Modules 2/3/1/5 of Andrew Ng's course respectively."
   },
   {
    "id": "p5-q5",
    "prompt": "Why does the roadmap place Andrew Ng's vendor-neutral course before framework tutorials like LangChain or CrewAI?",
    "options": [
     "Because frameworks require paid licenses first",
     "To understand agents from first principles before learning tools that implement the patterns",
     "Because frameworks cannot build agents",
     "To avoid writing any code"
    ],
    "answerIndex": 1,
    "explanation": "Pillar 5 goal: understand agents from first principles, vendor-neutral, before frameworks; Andrew Ng's course is the backbone."
   },
   {
    "id": "p5-q6",
    "prompt": "Besides the four design patterns, what other major skill does Andrew Ng's course include per its [KEY] row?",
    "options": [
     "GPU cluster administration",
     "Evals (evaluation of agentic systems)",
     "Mobile app packaging",
     "Database sharding"
    ],
    "answerIndex": 1,
    "explanation": "Row reads 4 patterns + evals (whole course) [KEY]: Agentic AI - Andrew Ng, DeepLearning.AI."
   },
   {
    "id": "p5-q7",
    "prompt": "Which resource supports building 8 agent projects in Pillar 5?",
    "options": [
     "Ed Donner - Agentic AI Engineering (repo)",
     "Ankit Bansal - RAG from First Principles",
     "Atlan - 12 Advanced RAG Techniques",
     "Logical Lenses - RAGAS explained"
    ],
    "answerIndex": 0,
    "explanation": "Build 8 agent projects maps to Ed Donner - Agentic AI Engineering (Udemy, repo)."
   },
   {
    "id": "p5-q8",
    "prompt": "What estimated length and role does the roadmap give Andrew Ng's Agentic AI course within Pillar 5?",
    "options": [
     "10-minute intro, optional skim",
     "Backbone of the pillar at roughly 7h45m including modules and notes repo",
     "4-minute overview replacing all reading",
     "22-minute read on memory layers"
    ],
    "answerIndex": 1,
    "explanation": "Roadmap lists Agentic AI - Andrew Ng at 7h45m as the whole-course [KEY] backbone covering patterns, evals, modules."
   }
  ]
 },
 {
  "pillarN": 6,
  "questions": [
   {
    "id": "p6-q1",
    "prompt": "In 'Context Engineering for Agents' (LangChain), the context window is compared to what scarce resource?",
    "options": [
     "CPU cache",
     "RAM",
     "Disk storage",
     "Network bandwidth"
    ],
    "answerIndex": 1,
    "explanation": "LangChain's article frames the context window as scarce RAM-like space, which is why you manage it deliberately with four moves."
   },
   {
    "id": "p6-q2",
    "prompt": "Which set names the four context-engineering moves from the LangChain article?",
    "options": [
     "Write, select, compress, isolate",
     "Prompt, parse, retrieve, rerank",
     "Plan, act, reflect, observe",
     "Chunk, embed, store, query"
    ],
    "answerIndex": 0,
    "explanation": "Per LangChain: write (persist), select (retrieve), compress (summarize/truncate), isolate (sub-agents)."
   },
   {
    "id": "p6-q3",
    "prompt": "In Anthropic's failure-mode taxonomy, 'context poisoning' means:",
    "options": [
     "Corrupted embedding vectors",
     "A hallucination enters context and keeps being referenced",
     "Context exceeding token limits",
     "Two tools returning clashing outputs"
    ],
    "answerIndex": 1,
    "explanation": "Effective context engineering (Anthropic): a hallucination that gets into context and is repeatedly trusted poisons later reasoning."
   },
   {
    "id": "p6-q4",
    "prompt": "'Context clash' in Anthropic's model occurs when:",
    "options": [
     "Token budget is exceeded mid-run",
     "Leftover junk from earlier steps conflicts with newer work",
     "Multiple sub-agents share one vector DB",
     "System prompt leaks to users"
    ],
    "answerIndex": 1,
    "explanation": "Anthropic lists clash as accumulated stale/misaligned content conflicting with current task state during long runs."
   },
   {
    "id": "p6-q5",
    "prompt": "Per the Weaviate memory article, short-term memory corresponds to:",
    "options": [
     "The vector store",
     "The log of past agent runs",
     "The model's context window",
     "Fine-tuned weights"
    ],
    "answerIndex": 2,
    "explanation": "Weaviate maps short-term memory to the context window itself; long-term lives in external stores like vector databases."
   },
   {
    "id": "p6-q6",
    "prompt": "Episodic memory for an agent is best described as:",
    "options": [
     "Static domain facts",
     "A record of past runs/interactions the agent can recall",
     "The system prompt",
     "Cached tool schemas"
    ],
    "answerIndex": 1,
    "explanation": "The three-layers memory write-up defines episodic memory as logs of previous sessions/runs an agent can retrieve."
   },
   {
    "id": "p6-q7",
    "prompt": "Which trio are named memory tools in 'AI Agent Memory Explained'?",
    "options": [
     "LangSmith, RAGAS, Zep",
     "Mem0, Letta, Zep",
     "Mem0, ColBERT, HyDE",
     "Letta, FastMCP, ADK"
    ],
    "answerIndex": 1,
    "explanation": "The article's taxonomy-plus-tools section covers Mem0, Letta, and Zep as purpose-built agent-memory layers."
   },
   {
    "id": "p6-q8",
    "prompt": "Per the Pillar 6 gap fill, where do most production agent bugs live?",
    "options": [
     "Inside model weights",
     "In handoffs between memory layers",
     "During tokenization",
     "In GPU utilization spikes"
    ],
    "answerIndex": 1,
    "explanation": "Gap fill: most production bugs live in handoffs between short-term (window), long-term (vector), and episodic layers."
   }
  ]
 },
 {
  "pillarN": 7,
  "questions": [
   {
    "id": "p7-q1",
    "prompt": "In ByteMonk's framing, LangGraph is primarily for:",
    "options": [
     "Chaining prompts sequentially",
     "Building stateful agent graphs with loops/control flow",
     "Hosting models",
     "Evaluating datasets"
    ],
    "answerIndex": 1,
    "explanation": "Stop Confusing LangChain/LangGraph/LangSmith (ByteMonk): LangGraph adds graph-based stateful control flow for agents; LangChain chains components."
   },
   {
    "id": "p7-q2",
    "prompt": "Which product is the observability/tracing layer per ByteMonk?",
    "options": [
     "LangChain",
     "LangGraph",
     "LangSmith",
     "LangServe"
    ],
    "answerIndex": 2,
    "explanation": "ByteMonk: LangSmith handles tracing, debugging, and evaluation; the other two build applications."
   },
   {
    "id": "p7-q3",
    "prompt": "In LangGraph (Krish Naik bootcamp), a 'node' is:",
    "options": [
     "A conditional branch only",
     "A function/step that updates shared state",
     "An edge weight",
     "A checkpoint file"
    ],
    "answerIndex": 1,
    "explanation": "Krish Naik's LangGraph section: nodes are functions executing steps and updating a shared state object; edges route between them."
   },
   {
    "id": "p7-q4",
    "prompt": "Human-in-the-loop (HITL) in LangGraph is implemented via:",
    "options": [
     "Interrupting the graph before chosen nodes for approval",
     "A separate UI framework",
     "Fine-tuning on human data",
     "Disabling checkpoints"
    ],
    "answerIndex": 0,
    "explanation": "Krish Naik covers HITL as interrupts that pause execution at designated nodes so humans approve before continuing."
   },
   {
    "id": "p7-q5",
    "prompt": "What enables LangGraph memory across steps or sessions?",
    "options": [
     "Global Python variables",
     "Checkpointer/persistence of state threads",
     "Recompiling the graph",
     "Larger context windows"
    ],
    "answerIndex": 1,
    "explanation": "LangGraph persistence uses checkpointers saving state per thread, giving both intra-run and cross-session memory."
   },
   {
    "id": "p7-q6",
    "prompt": "CrewAI's core abstraction is:",
    "options": [
     "Role-based crews of collaborating agents with tasks",
     "Low-rank adapters",
     "Vector indexes",
     "HTTP middleware"
    ],
    "answerIndex": 0,
    "explanation": "Ed Donner's Agentic AI Engineering introduces CrewAI as role-defined agents organized into crews executing tasks."
   },
   {
    "id": "p7-q7",
    "prompt": "Google's Agent Development Kit is abbreviated:",
    "options": [
     "ADK",
     "AGK",
     "MCP",
     "SDK"
    ],
    "answerIndex": 0,
    "explanation": "Ed Donner Wks 2-5 cover frameworks including Google's ADK alongside OpenAI SDK, AutoGen, CrewAI."
   },
   {
    "id": "p7-q8",
    "prompt": "First debugging move for an unexpected agent run in LangSmith is:",
    "options": [
     "Retrain the model",
     "Inspect the trace of inputs/outputs per step",
     "Increase temperature",
     "Delete all checkpoints"
    ],
    "answerIndex": 1,
    "explanation": "LangSmith docs walkthroughs center on reading traces step-by-step to find where a run went wrong."
   }
  ]
 },
 {
  "pillarN": 8,
  "questions": [
   {
    "id": "p8-q1",
    "prompt": "In 'How MCP actually works' (Google Cloud Tech), MCP solves what problem?",
    "options": [
     "Model training speed",
     "M×N integration explosion between AI apps and data/tools via one open standard",
     "GPU memory limits",
     "Prompt tokenization cost"
    ],
    "answerIndex": 1,
    "explanation": "Google Cloud Tech frames MCP as USB-C-for-AI: one standard replacing bespoke app-to-tool integrations (the M×N problem)."
   },
   {
    "id": "p8-q2",
    "prompt": "Per the CampusX MCP Trilogy, the correct learning order is:",
    "options": [
     "Build → Security → Why",
     "Why → Architecture → Lifecycle → Build",
     "Security → Sampling → Architecture",
     "Lifecycle → Why → Build"
    ],
    "answerIndex": 1,
    "explanation": "CampusX's playlist sequences motivation first (why MCP), then architecture, then lifecycle, then building servers/clients."
   },
   {
    "id": "p8-q3",
    "prompt": "Why is tool poisoning considered a supply-chain-style attack, worse than ordinary prompt injection?",
    "options": [
     "It requires physical access to the host machine",
     "It only affects open-source models",
     "It arrives through a third-party server you chose to integrate, poisoning a trusted channel rather than a single user input",
     "It bypasses TLS encryption entirely"
    ],
    "answerIndex": 2,
    "explanation": "Lens' MCP Security threat model frames poisoned tools as supply-chain attacks: trust flows from an integrated dependency, not one-off user text."
   },
   {
    "id": "p8-q4",
    "prompt": "In MCP, what does the SAMPLING primitive let a server do?",
    "options": [
     "Compress tool outputs before returning them",
     "Rate-limit client requests across sessions",
     "Randomly select which tools stay enabled",
     "Request LLM completions through the client during a tool flow"
    ],
    "answerIndex": 3,
    "explanation": "Web Dev Simplified's Ultimate MCP Crash Course covers sampling as the client-side primitive intro videos skip: servers ask the client's LLM to generate completions."
   },
   {
    "id": "p8-q5",
    "prompt": "Which defense bundle matches the roadmap's guidance for securing MCP servers?",
    "options": [
     "Auto-update servers without review to patch quickly",
     "Allow broad write access but log all calls",
     "Trust the model to refuse malicious instructions",
     "Pin version plus content hash, default read-only, re-approve after changes, sandbox execution, validate responses before context"
    ],
    "answerIndex": 3,
    "explanation": "The Pillar 8 gap-fill lists pinning (version + hash), read-only default, re-approval after changes, sandboxing, and validating responses pre-context (SentinelOne guide)."
   },
   {
    "id": "p8-q6",
    "prompt": "A rug pull (or line jumping) attack occurs when...",
    "options": [
     "A server drains funds from a connected crypto wallet",
     "Tool behavior or descriptions change maliciously AFTER user approval",
     "The client downgrades to an older protocol version",
     "Two servers claim the same tool name simultaneously"
    ],
    "answerIndex": 1,
    "explanation": "OWASP Foundation's MCP Tool Poisoning write-up covers rug pulls: approved tools silently turning malicious later - hence re-approval after any change."
   },
   {
    "id": "p8-q7",
    "prompt": "Which resource teaches building a production-ready MCP server with FastMCP and auth?",
    "options": [
     "Google Cloud Tech - How MCP actually works",
     "Microsoft - MCP for Beginners repo",
     "codebasics - Production-Ready MCP Server in 90 min",
     "CampusX - MCP Trilogy playlist"
    ],
    "answerIndex": 2,
    "explanation": "codebasics' 90-minute video builds a production-grade server using FastMCP with authentication; Google Cloud Tech and CampusX cover concepts instead."
   },
   {
    "id": "p8-q8",
    "prompt": "Which Udemy option explicitly covers OAuth 2.1 for MCP development?",
    "options": [
     "Nikolai Schuler - Complete MCP Developer Guide",
     "Ed Donner - Agentic AI Engineering",
     "Andrew Ng - Agentic AI",
     "Krish Naik Bootcamp"
    ],
    "answerIndex": 0,
    "explanation": "Nikolai Schuler's Complete MCP Developer Guide covers OAuth 2.1; Eden Marco's MCP Crash Course is the alternative that includes security."
   }
  ]
 },
 {
  "pillarN": 9,
  "questions": [
   {
    "id": "p9-q1",
    "prompt": "Why do traditional metrics like BLEU and ROUGE fail for RAG and agent evaluation?",
    "options": [
     "They require GPU acceleration unavailable in CI",
     "They were patented and cannot be licensed",
     "They measure wording overlap, not whether answers are grounded in retrieved facts",
     "They only work for translation tasks in non-English languages"
    ],
    "answerIndex": 2,
    "explanation": "The Pillar 9 gap-fill says BLEU/ROUGE measure wording, not grounding - RAGAS replaces them since no human labels are needed."
   },
   {
    "id": "p9-q2",
    "prompt": "What is RAGAS's key practical advantage over classic reference-based metrics?",
    "options": [
     "It needs no human-written labels or golden answers",
     "It trains a custom judge model per project",
     "It runs only on proprietary APIs",
     "It eliminates the need for retrieval entirely"
    ],
    "answerIndex": 0,
    "explanation": "Logical Lenses' RAG Evaluation, RAGAS explained shows faithfulness plus context precision/recall computed without human labels - runnable locally per Analytics Vidhya."
   },
   {
    "id": "p9-q3",
    "prompt": "For evaluating agent behaviors, what scoring style does the roadmap recommend over a vague 1-10 LLM-judge score?",
    "options": [
     "Average star ratings across many runs",
     "A percentage similarity score against a gold answer",
     "No scoring at all - ship and monitor",
     "A rubric with a binary pass/fail score per behavior"
    ],
    "answerIndex": 3,
    "explanation": "Per Andrew Ng's Agentic AI Module 4 guidance echoed in the gap-fill, binary rubric scores per behavior beat vague 1-10 judge ratings."
   },
   {
    "id": "p9-q4",
    "prompt": "According to Andrew Ng, what is the single biggest predictor of agent-building success?",
    "options": [
     "Evaluation-driven development",
     "Fine-tuning base models first",
     "Using the largest available model",
     "Multi-agent architectures everywhere"
    ],
    "answerIndex": 0,
    "explanation": "The Pillar 9 goal cites Andrew Ng: evaluation-driven development is the single biggest predictor of agent-building success (Module 4)."
   },
   {
    "id": "p9-q5",
    "prompt": "In RAG evaluation, how should you correctly split your measurement concerns?",
    "options": [
     "Score everything with one overall accuracy number",
     "Measure faithfulness for generation grounding separately from context precision/recall for retrieval",
     "Evaluate only final outputs and ignore retrieved chunks",
     "Let the LLM self-report correctness percentages"
    ],
    "answerIndex": 1,
    "explanation": "Logical Lenses' RAGAS video separates retrieval quality (context precision/recall) from generation quality (faithfulness) - measure each independently."
   },
   {
    "id": "p9-q6",
    "prompt": "How should a RAGAS harness fit into your development workflow?",
    "options": [
     "Run once before major releases only",
     "Delegate evaluation to end users via feedback forms",
     "Treat it like unit tests running in CI on every change",
     "Skip it when prompts feel subjectively good"
    ],
    "answerIndex": 2,
    "explanation": "The gap-fill says treat RAGAS like unit tests in CI on every change; the RAGAS tutorial write-up shows a local no-API setup."
   },
   {
    "id": "p9-q7",
    "prompt": "Andrew Ng's Agentic AI Module 4 covers which evaluation trio flagged KEY in the roadmap?",
    "options": [
     "Chunking, embedding, reranking",
     "Objective metrics vs LLM-judge, error analysis, traces",
     "LoRA rank, alpha, dropout",
     "OAuth scopes, tokens, refresh flows"
    ],
    "answerIndex": 1,
    "explanation": "Module 4 of Andrew Ng's Agentic AI course covers objective vs LLM-judge evals, error analysis, and trace inspection - marked do-not-skip."
   },
   {
    "id": "p9-q8",
    "prompt": "When debugging why an agent failed mid-run, which tool does the roadmap point to for inspecting step-by-step traces?",
    "options": [
     "Zep",
     "Mem0",
     "LangSmith",
     "ColBERT"
    ],
    "answerIndex": 2,
    "explanation": "LangSmith docs provide tracing and observability walkthroughs to inspect each node's inputs, outputs, and errors during a run."
   }
  ]
 },
 {
  "pillarN": 10,
  "questions": [
   {
    "id": "p10-q1",
    "prompt": "Within the OWASP Top-10 for LLMs, where does RAG security primarily live?",
    "options": [
     "LLM03 Supply Chain",
     "LLM08 Vector & Embedding Weaknesses",
     "LLM09 Misinformation",
     "LLM05 Improper Output Handling"
    ],
    "answerIndex": 1,
    "explanation": "The roadmap notes LLM08 Vector & Embedding Weaknesses is where RAG security lives - tie it back to Pillar 3; Giskard's overview lists all ten risks."
   },
   {
    "id": "p10-q2",
    "prompt": "Which OWASP risk maps directly to agent and MCP deployments?",
    "options": [
     "LLM06 Excessive Agency",
     "LLM02 Sensitive Info Disclosure",
     "LLM04 Data & Model Poisoning",
     "LLM07 System Prompt Leakage"
    ],
    "answerIndex": 0,
    "explanation": "Per the roadmap, LLM06 Excessive Agency is the agent/MCP risk - granting tools more autonomy than needed - tie it back to Pillar 8."
   },
   {
    "id": "p10-q3",
    "prompt": "LLM07 System Prompt Leakage refers to:",
    "options": [
     "Prompts exceeding maximum token limits",
     "System prompts being exposed, revealing instructions meant to stay private",
     "Losing prompt history during application restarts",
     "Encoding errors in multilingual prompts"
    ],
    "answerIndex": 1,
    "explanation": "Giskard's OWASP Top-10 for LLM 2025 overview counts system prompt leakage among the ten risks: private instructions leaking to end users."
   },
   {
    "id": "p10-q4",
    "prompt": "LLM10 Unbounded Consumption best describes which failure mode?",
    "options": [
     "Unlimited free-tier usage granted by accident",
     "Models consuming their own hallucinated outputs recursively",
     "Context windows growing beyond hardware limits",
     "Runaway inference costs or resource exhaustion from unchecked usage"
    ],
    "answerIndex": 3,
    "explanation": "Giskard's overview defines Unbounded Consumption as uncontrolled resource use - cost and denial-of-service exposure when queries go uncapped."
   },
   {
    "id": "p10-q5",
    "prompt": "Prompt injection (LLM01) comes in two delivery forms. Which pair is correct?",
    "options": [
     "Verbal and written",
     "Batch and streaming",
     "Direct (user-crafted) and indirect (hidden in content the model reads)",
     "Local and cloud"
    ],
    "answerIndex": 2,
    "explanation": "IT Bulls' OWASP LLM01 explained distinguishes direct injection typed by users from indirect payloads planted in documents, emails, or web pages."
   },
   {
    "id": "p10-q6",
    "prompt": "Improper Output Handling (LLM05) occurs when:",
    "options": [
     "An LLM's untrusted output is passed downstream without validation - into shells, SQL, or browsers",
     "Outputs exceed temperature sampling bounds",
     "Responses arrive slower than the SLA allows",
     "Streaming responses drop mid-generation"
    ],
    "answerIndex": 0,
    "explanation": "The OWASP Top-10 Practical Guide flags treating model output as trusted code or query input - sanitize before executing downstream."
   },
   {
    "id": "p10-q7",
    "prompt": "LLM03 Supply Chain covers compromises in:",
    "options": [
     "Network cables and routers",
     "User session cookies",
     "Third-party components - packages, plugins, pre-trained models, or fine-tuning data",
     "Browser cache storage"
    ],
    "answerIndex": 2,
    "explanation": "Ali Dorri's OWASP Top-10 deep dive places vulnerable dependencies and tainted models under Supply Chain - distinct from LLM04 training-data poisoning."
   },
   {
    "id": "p10-q8",
    "prompt": "Why does the roadmap call learning only prompt injection the biggest gap in typical LLM security study?",
    "options": [
     "Injection videos are usually too long",
     "Nine other named risks remain uncovered beyond injection",
     "Injection only matters for chatbots",
     "The topic needs mathematics most learners lack"
    ],
    "answerIndex": 1,
    "explanation": "One injection video leaves 9 of 10 risks uncovered; Giskard's 4-minute OWASP Top-10 for LLM 2025 overview names all ten, LLM01 through LLM10."
   }
  ]
 }
];
