// AUTO-GENERATED by scripts/build-roadmap.ts — edit LLM_Agentic_AI_Roadmap_Tracker.md and regenerate.
import type { RoadmapData } from "./types";

export const ROADMAP: RoadmapData = {
  "pillars": [
    {
      "number": 1,
      "slugId": "pillar-1",
      "title": "Transformer & LLM Internals",
      "focus": "",
      "goal": "explain how an LLM works end-to-end without deep math. 3Blue1Brown chapters are the visual gold standard — watch in order",
      "sections": [
        {
          "id": "pillar-1",
          "title": "Core",
          "items": [
            {
              "id": "p1-big-picture-what-an-llm-is",
              "subtopic": "Big-picture: what an LLM is",
              "resourceName": "LLMs explained briefly — 3B1B (playlist)",
              "url": "https://www.youtube.com/watch?v=LPZh9BOjkQs",
              "urlType": "video",
              "lengthLabel": "8m",
              "lengthMinutes": 8,
              "isKey": false
            },
            {
              "id": "p1-full-forward-pass-embeddings-softmax",
              "subtopic": "Full forward pass, embeddings, softmax",
              "resourceName": "Ch.5 Transformers, the tech behind LLMs — 3B1B",
              "url": "https://www.youtube.com/watch?v=wjZofJX0v4M",
              "urlType": "video",
              "lengthLabel": "27m",
              "lengthMinutes": 27,
              "isKey": false
            },
            {
              "id": "p1-attention-q-k-v-masking-multi-head",
              "subtopic": "Attention: Q/K/V, masking, multi-head",
              "resourceName": "Ch.6 Attention, step-by-step — 3B1B",
              "url": "https://www.youtube.com/watch?v=eMlx5fFNoYc",
              "urlType": "video",
              "lengthLabel": "26m",
              "lengthMinutes": 26,
              "isKey": true
            },
            {
              "id": "p1-how-facts-live-in-mlp-layers-often-skipped",
              "subtopic": "How facts live in MLP layers (often skipped)",
              "resourceName": "Ch.7 How might LLMs store facts — 3B1B",
              "url": "https://www.youtube.com/watch?v=9-Jl0dxWQs8",
              "urlType": "video",
              "lengthLabel": "23m",
              "lengthMinutes": 23,
              "isKey": false
            },
            {
              "id": "p1-tokenization-bpe-positional-encoding",
              "subtopic": "Tokenization/BPE + positional encoding",
              "resourceName": "Let's build GPT from scratch — Karpathy",
              "url": "https://www.youtube.com/watch?v=kCc8FmEb1nY",
              "urlType": "video",
              "lengthLabel": "1h56m",
              "lengthMinutes": 116,
              "isKey": false
            }
          ]
        }
      ],
      "callouts": [
        {
          "sectionId": "pillar-1",
          "text": "Gap fill:: Most people only watch the attention video and miss (1) positional encoding — why order must be injected (Karpathy's build-GPT), (2) MLP/feed-forward layers store factual knowledge (3B1B Ch.7). Add both. Skip 3B1B Ch.1–4 (neural-net basics/backprop) unless you want them — not needed to build."
        }
      ]
    },
    {
      "number": 2,
      "slugId": "pillar-2",
      "title": "LLM App Fundamentals",
      "focus": "",
      "goal": "go from \"I can call an API\" to \"I can ship an LLM feature.\" Ed Donner's course (Ollama-first, laptop-friendly) is strongest here",
      "sections": [
        {
          "id": "pillar-2",
          "title": "Core",
          "items": [
            {
              "id": "p2-apis-prompts-streaming-multi-provider",
              "subtopic": "APIs, prompts, streaming, multi-provider",
              "resourceName": "Ed Donner — LLM Engineering, Wks 1–2 (repo)",
              "url": "https://github.com/ed-donner/llm_engineering",
              "urlType": "repo",
              "lengthLabel": "Udemy",
              "lengthMinutes": null,
              "isKey": false
            },
            {
              "id": "p2-tool-function-calling",
              "subtopic": "Tool / function calling",
              "resourceName": "Ed Donner Wk2 + ReAct explainer",
              "url": "https://www.udemy.com/courses/search/?q=llm+engineering+ed+donner",
              "urlType": "course",
              "lengthLabel": "Udemy+6m",
              "lengthMinutes": 6,
              "isKey": false
            },
            {
              "id": "p2-fast-uis-gradio",
              "subtopic": "Fast UIs (Gradio)",
              "resourceName": "Ed Donner Wk2",
              "url": "https://www.udemy.com/courses/search/?q=llm+engineering+ed+donner",
              "urlType": "course",
              "lengthLabel": "Udemy",
              "lengthMinutes": null,
              "isKey": false
            },
            {
              "id": "p2-open-source-models-huggingface",
              "subtopic": "Open-source models & HuggingFace",
              "resourceName": "Ed Donner Wk3",
              "url": "https://www.udemy.com/courses/search/?q=llm+engineering+ed+donner",
              "urlType": "course",
              "lengthLabel": "Udemy",
              "lengthMinutes": null,
              "isKey": false
            },
            {
              "id": "p2-model-selection-leaderboards",
              "subtopic": "Model selection / leaderboards",
              "resourceName": "Ed Donner Wk4",
              "url": "https://www.udemy.com/courses/search/?q=llm+engineering+ed+donner",
              "urlType": "course",
              "lengthLabel": "Udemy",
              "lengthMinutes": null,
              "isKey": false
            },
            {
              "id": "p2-structured-output-json-pydantic",
              "subtopic": "Structured output (JSON/Pydantic)",
              "resourceName": "Structured outputs — OpenAI docs",
              "url": "https://developers.openai.com/api/docs/guides/structured-outputs",
              "urlType": "doc",
              "lengthLabel": "read",
              "lengthMinutes": null,
              "isKey": false
            }
          ]
        }
      ],
      "callouts": []
    },
    {
      "number": 3,
      "slugId": "pillar-3",
      "title": "RAG (Basic → Advanced → Eval)",
      "focus": "",
      "goal": "build RAG that works in production. Biggest hidden gap — basic tutorials stop at \"embed + top-k,\" real systems need hybrid search, reranking, evaluation",
      "sections": [
        {
          "id": "pillar-3-3a-foundations",
          "title": "3a · Foundations",
          "items": [
            {
              "id": "p3-why-rag-embeddings-vector-db-cosine",
              "subtopic": "Why RAG; embeddings; vector DB; cosine",
              "resourceName": "RAG from First Principles — Ankit Bansal",
              "url": null,
              "urlType": "unverified",
              "lengthLabel": "38m",
              "lengthMinutes": 38,
              "isKey": true
            },
            {
              "id": "p3-build-a-real-rag-app",
              "subtopic": "Build a real RAG app",
              "resourceName": "Ed Donner — LLM Engineering, Wk5 (knowledge-worker)",
              "url": "https://github.com/ed-donner/llm_engineering",
              "urlType": "repo",
              "lengthLabel": "Udemy",
              "lengthMinutes": null,
              "isKey": false
            }
          ]
        },
        {
          "id": "pillar-3-3b-advanced-retrieval-the-gap",
          "title": "3b · Advanced retrieval (the gap)",
          "items": [
            {
              "id": "p3-hybrid-search-bm25-dense-rrf",
              "subtopic": "Hybrid search: BM25 + dense + RRF",
              "resourceName": "Production RAG w/ LangChain & Vector DBs — freeCodeCamp",
              "url": "https://www.youtube.com/watch?v=mHxLXzYjQRE",
              "urlType": "video",
              "lengthLabel": "7h38m",
              "lengthMinutes": 458,
              "isKey": false
            },
            {
              "id": "p3-reranking-cross-encoders-colbert",
              "subtopic": "Reranking (cross-encoders/ColBERT)",
              "resourceName": "Advanced RAG techniques — Field Guide to AI",
              "url": "https://fieldguidetoai.com/guides/advanced-rag-techniques",
              "urlType": "read",
              "lengthLabel": "9m read",
              "lengthMinutes": 9,
              "isKey": false
            },
            {
              "id": "p3-query-transforms-hyde-multi-query",
              "subtopic": "Query transforms (HyDE, multi-query)",
              "resourceName": "Advanced RAG: hybrid, reranking, query expansion",
              "url": "https://reynaldineo.com/blog/exploring-advance-retrieval-techniques",
              "urlType": "read",
              "lengthLabel": "read",
              "lengthMinutes": null,
              "isKey": false
            },
            {
              "id": "p3-chunking-parent-child-sentence-window",
              "subtopic": "Chunking: parent-child, sentence-window",
              "resourceName": "12 Advanced RAG Techniques (2026) — Atlan",
              "url": "https://atlan.com/know/advanced-rag-techniques/",
              "urlType": "read",
              "lengthLabel": "read",
              "lengthMinutes": null,
              "isKey": false
            },
            {
              "id": "p3-graphrag-raptor-contextual-retrieval",
              "subtopic": "GraphRAG / RAPTOR / Contextual Retrieval",
              "resourceName": "Same Atlan guide (techniques 8–12)",
              "url": "https://atlan.com/know/advanced-rag-techniques/",
              "urlType": "read",
              "lengthLabel": "read",
              "lengthMinutes": null,
              "isKey": false
            }
          ]
        },
        {
          "id": "pillar-3-3c-rag-evaluation-ragas-key",
          "title": "3c · RAG evaluation (RAGAS) [KEY]",
          "items": [
            {
              "id": "p3-metrics-faithfulness-context-precision-recall",
              "subtopic": "Metrics: faithfulness, context precision/recall",
              "resourceName": "RAG Evaluation, RAGAS explained — Logical Lenses",
              "url": "https://www.youtube.com/watch?v=7_LTU0LA374",
              "urlType": "video",
              "lengthLabel": "12m",
              "lengthMinutes": 12,
              "isKey": false
            },
            {
              "id": "p3-ragas-hands-on-in-python",
              "subtopic": "RAGAS hands-on in Python",
              "resourceName": "RAG Evaluation Metrics Tutorial — Analytics Vidhya",
              "url": "https://www.analyticsvidhya.com/blog/2024/05/a-beginners-guide-to-evaluating-rag-pipelines-using-ragas/",
              "urlType": "read",
              "lengthLabel": "6m",
              "lengthMinutes": 6,
              "isKey": false
            }
          ]
        }
      ],
      "callouts": [
        {
          "sectionId": "pillar-3-3c-rag-evaluation-ragas-key",
          "text": "Gap fill:: Basic RAG scores ~44% factual accuracy; adding hybrid search + reranking pushes it toward ~63% (CRAG benchmark). Do NOT ship RAG without: (1) a reranker, (2) hybrid (BM25+dense) retrieval, (3) a RAGAS eval harness run in CI on every change. Rule of thumb: measure retrieval quality (context precision/recall) separately from generation quality (faithfulness)."
        }
      ]
    },
    {
      "number": 4,
      "slugId": "pillar-4",
      "title": "Fine-Tuning (LoRA/QLoRA)",
      "focus": "",
      "goal": "know when NOT to fine-tune, and how LoRA/QLoRA make it cheap. Optional for most app work — but a common interview topic",
      "sections": [
        {
          "id": "pillar-4",
          "title": "Core",
          "items": [
            {
              "id": "p4-the-one-rule-fine-tune-behavior-not-knowledge",
              "subtopic": "The one rule: fine-tune = behavior, not knowledge",
              "resourceName": "How to Fine-Tune an LLM (2026) — read intro",
              "url": "https://www.layer3labs.io/guides/how-to-fine-tune-an-llm",
              "urlType": "read",
              "lengthLabel": "read",
              "lengthMinutes": null,
              "isKey": true
            },
            {
              "id": "p4-lora-qlora-rank-alpha-dropout-4-bit-nf4",
              "subtopic": "LoRA/QLoRA + rank, alpha, dropout, 4-bit NF4",
              "resourceName": "LoRA & QLoRA In-Depth — Mark Hennings",
              "url": "https://www.youtube.com/watch?v=t1caDsMzWBk",
              "urlType": "video",
              "lengthLabel": "15m",
              "lengthMinutes": 15,
              "isKey": false
            },
            {
              "id": "p4-quick-peft-overview-lora-qlora-dora",
              "subtopic": "Quick PEFT overview (LoRA/QLoRA/DoRA)",
              "resourceName": "PEFT Explained — Arivu",
              "url": null,
              "urlType": "unverified",
              "lengthLabel": "4m",
              "lengthMinutes": 4,
              "isKey": false
            },
            {
              "id": "p4-end-to-end-deep-dive-code",
              "subtopic": "End-to-end deep dive + code",
              "resourceName": "LoRA & QLoRA Explained Simply — Sunny Savita",
              "url": "https://www.youtube.com/watch?v=cO6Ly7mIziQ",
              "urlType": "video",
              "lengthLabel": "1h27m",
              "lengthMinutes": 87,
              "isKey": false
            },
            {
              "id": "p4-fine-tune-in-the-course",
              "subtopic": "Fine-tune in the course",
              "resourceName": "Ed Donner — LLM Engineering, Wks 6–7",
              "url": "https://www.udemy.com/courses/search/?q=llm+engineering+ed+donner",
              "urlType": "course",
              "lengthLabel": "Udemy",
              "lengthMinutes": null,
              "isKey": false
            }
          ]
        }
      ],
      "callouts": [
        {
          "sectionId": "pillar-4",
          "text": "Gap fill:: Interviewers love \"RAG vs fine-tuning?\" — RAG for fresh/changing facts & citations; fine-tuning for format, tone, domain vocabulary, reasoning style. Never fine-tune to \"teach it your documents.\" Know QLoRA specifics: 4-bit NF4 quantization of the frozen base + small trainable low-rank adapters on the attention projections."
        }
      ]
    },
    {
      "number": 5,
      "slugId": "pillar-5",
      "title": "Agents & Design Patterns",
      "focus": "",
      "goal": "understand agents from first principles (vendor-neutral) before frameworks. Andrew Ng's course is the backbone",
      "sections": [
        {
          "id": "pillar-5",
          "title": "Core",
          "items": [
            {
              "id": "p5-agent-vs-workflow-react-loop",
              "subtopic": "Agent vs workflow; ReAct loop",
              "resourceName": "AI Agents, Clearly Explained — Jeff Su",
              "url": "https://www.youtube.com/watch?v=FwOTs4UxQS4",
              "urlType": "video",
              "lengthLabel": "10m",
              "lengthMinutes": 10,
              "isKey": true
            },
            {
              "id": "p5-react-in-practice",
              "subtopic": "ReAct in practice",
              "resourceName": "ReAct Agents, clearly explained — Akshay Pachaar",
              "url": "https://www.youtube.com/watch?v=vFdIrZyKEwQ",
              "urlType": "video",
              "lengthLabel": "6m",
              "lengthMinutes": 6,
              "isKey": false
            },
            {
              "id": "p5-4-patterns-evals-whole-course",
              "subtopic": "4 patterns + evals (whole course)",
              "resourceName": "Agentic AI — Andrew Ng, DeepLearning.AI",
              "url": "https://www.deeplearning.ai/courses/agentic-ai/",
              "urlType": "read",
              "lengthLabel": "7h45m",
              "lengthMinutes": 465,
              "isKey": true
            },
            {
              "id": "p5-reflection-tool-use-planning-multi-agent",
              "subtopic": "Reflection / Tool use / Planning / Multi-agent",
              "resourceName": "Same course, Modules 2/3/1/5 · notes repo",
              "url": "https://github.com/rczhen/agentic-ai-course-notes",
              "urlType": "repo",
              "lengthLabel": "incl.",
              "lengthMinutes": null,
              "isKey": false
            },
            {
              "id": "p5-build-8-agent-projects",
              "subtopic": "Build 8 agent projects",
              "resourceName": "Ed Donner — Agentic AI Engineering (repo)",
              "url": "https://github.com/ed-donner/agents",
              "urlType": "repo",
              "lengthLabel": "Udemy",
              "lengthMinutes": null,
              "isKey": false
            }
          ]
        }
      ],
      "callouts": []
    },
    {
      "number": 6,
      "slugId": "pillar-6",
      "title": "Context Engineering & Memory",
      "focus": "",
      "goal": "the #1 skill for reliable agents in 2025–26, and almost always missing from course lists",
      "sections": [
        {
          "id": "pillar-6",
          "title": "Core",
          "items": [
            {
              "id": "p6-context-window-as-scarce-ram-write-select-compre",
              "subtopic": "Context window as scarce RAM; write/select/compress/isolate",
              "resourceName": "Context Engineering for Agents — LangChain",
              "url": "https://www.langchain.com/blog/context-engineering-for-agents",
              "urlType": "read",
              "lengthLabel": "14m read",
              "lengthMinutes": 14,
              "isKey": true
            },
            {
              "id": "p6-anthropic-s-mental-model-failure-modes",
              "subtopic": "Anthropic's mental model + failure modes",
              "resourceName": "Effective context engineering — Anthropic",
              "url": "https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents",
              "urlType": "read",
              "lengthLabel": "read",
              "lengthMinutes": null,
              "isKey": false
            },
            {
              "id": "p6-short-vs-long-vs-episodic-memory",
              "subtopic": "Short vs long vs episodic memory",
              "resourceName": "Context Engineering: LLM Memory & Retrieval — Weaviate",
              "url": "https://weaviate.io/blog/context-engineering",
              "urlType": "read",
              "lengthLabel": "22m read",
              "lengthMinutes": 22,
              "isKey": false
            },
            {
              "id": "p6-memory-taxonomy-tools-mem0-letta-zep",
              "subtopic": "Memory taxonomy + tools (Mem0, Letta, Zep)",
              "resourceName": "AI Agent Memory Explained — three layers",
              "url": "https://machinelearningmastery.com/ai-agent-memory-explained-in-3-levels-of-difficulty/",
              "urlType": "read",
              "lengthLabel": "8m read",
              "lengthMinutes": 8,
              "isKey": false
            }
          ]
        }
      ],
      "callouts": [
        {
          "sectionId": "pillar-6",
          "text": "Gap fill — why this matters:: Cognition & Anthropic both call context engineering \"the #1 job of engineers building agents.\" Long runs cause context poisoning, distraction, confusion, and clash. Learn the four moves: write (persist), select (retrieve), compress (summarize/truncate), isolate (sub-agents). Memory = engineering you add: short-term (context window), long-term (vector store), episodic (log of past runs). Most production bugs live in the handoffs between these layers."
        }
      ]
    },
    {
      "number": 7,
      "slugId": "pillar-7",
      "title": "Frameworks",
      "focus": "",
      "goal": "fluency in the tools that implement the patterns. Fix vocabulary first, then go deep on LangGraph (the one interviewers ask about most)",
      "sections": [
        {
          "id": "pillar-7",
          "title": "Core",
          "items": [
            {
              "id": "p7-langchain-vs-langgraph-vs-langsmith",
              "subtopic": "LangChain vs LangGraph vs LangSmith",
              "resourceName": "Stop Confusing LangChain/LangGraph/LangSmith — ByteMonk",
              "url": "https://www.youtube.com/watch?v=e-GR3PlEOVU",
              "urlType": "video",
              "lengthLabel": "12m",
              "lengthMinutes": 12,
              "isKey": true
            },
            {
              "id": "p7-langgraph-state-nodes-edges-memory-hitl",
              "subtopic": "LangGraph: state, nodes, edges, memory, HITL",
              "resourceName": "Krish Naik Bootcamp · free 10-hr",
              "url": "https://www.youtube.com/watch?v=rV3HJ4LEZ7k",
              "urlType": "video",
              "lengthLabel": "Udemy/11h",
              "lengthMinutes": 660,
              "isKey": false
            },
            {
              "id": "p7-langgraph-full-free-course",
              "subtopic": "LangGraph full free course",
              "resourceName": "LangGraph complete course — freeCodeCamp",
              "url": "https://www.youtube.com/watch?v=jGg_1h0qzaM",
              "urlType": "video",
              "lengthLabel": "3h",
              "lengthMinutes": 180,
              "isKey": false
            },
            {
              "id": "p7-crewai-openai-sdk-autogen-adk",
              "subtopic": "CrewAI / OpenAI SDK / AutoGen / ADK",
              "resourceName": "Ed Donner — Agentic AI Engineering (Wks 2–5)",
              "url": "https://github.com/ed-donner/agents",
              "urlType": "repo",
              "lengthLabel": "Udemy",
              "lengthMinutes": null,
              "isKey": false
            },
            {
              "id": "p7-tracing-debugging-langsmith",
              "subtopic": "Tracing & debugging (LangSmith)",
              "resourceName": "LangSmith docs & walkthroughs",
              "url": "https://docs.langchain.com/langsmith/",
              "urlType": "doc",
              "lengthLabel": "docs",
              "lengthMinutes": null,
              "isKey": false
            }
          ]
        }
      ],
      "callouts": []
    },
    {
      "number": 8,
      "slugId": "pillar-8",
      "title": "Model Context Protocol (MCP)",
      "focus": "",
      "goal": "understand, build, AND secure MCP. Intro videos cover why/architecture but skip client-side primitives and the entire MCP security attack class",
      "sections": [
        {
          "id": "pillar-8-8a-concepts-build",
          "title": "8a · Concepts & build",
          "items": [
            {
              "id": "p8-why-mcp-2-min-mental-model",
              "subtopic": "Why MCP (2-min mental model)",
              "resourceName": "How MCP actually works — Google Cloud Tech",
              "url": "https://www.youtube.com/watch?v=cGuyrANVi4A",
              "urlType": "video",
              "lengthLabel": "8m",
              "lengthMinutes": 8,
              "isKey": false
            },
            {
              "id": "p8-why-architecture-lifecycle-build",
              "subtopic": "Why → Architecture → Lifecycle → Build",
              "resourceName": "MCP Trilogy playlist — CampusX",
              "url": "https://www.youtube.com/playlist?list=PLKnIA16_Rmva_oZ9F4ayUu9qcWgF7Fyc0",
              "urlType": "read",
              "lengthLabel": "8 vids",
              "lengthMinutes": null,
              "isKey": false
            },
            {
              "id": "p8-full-build-server-client-tools-resources-prompts",
              "subtopic": "Full build: server+client, tools, resources, prompts, SAMPLING",
              "resourceName": "Ultimate MCP Crash Course — Web Dev Simplified",
              "url": "https://www.youtube.com/watch?v=ZoZxQwp1PiM",
              "urlType": "video",
              "lengthLabel": "1h15m",
              "lengthMinutes": 75,
              "isKey": true
            },
            {
              "id": "p8-production-server-w-fastmcp-auth",
              "subtopic": "Production server w/ FastMCP + auth",
              "resourceName": "Production-Ready MCP Server in 90 min — codebasics",
              "url": "https://www.youtube.com/watch?v=oG9yVmggMnE",
              "urlType": "video",
              "lengthLabel": "1h42m",
              "lengthMinutes": 102,
              "isKey": false
            },
            {
              "id": "p8-hands-on-labs-multi-language",
              "subtopic": "Hands-on labs (multi-language)",
              "resourceName": "MCP for Beginners — Microsoft (GitHub)",
              "url": "https://github.com/microsoft/mcp-for-beginners",
              "urlType": "repo",
              "lengthLabel": "repo",
              "lengthMinutes": null,
              "isKey": false
            },
            {
              "id": "p8-all-in-one-course-incl-security",
              "subtopic": "All-in-one course (incl. security)",
              "resourceName": "Eden Marco — MCP Crash Course *or* Nikolai Schuler — Complete MCP Developer Guide (OAuth 2.1)",
              "url": "https://www.udemy.com/course/model-context-protocol/",
              "urlType": "course",
              "lengthLabel": "Udemy",
              "lengthMinutes": null,
              "isKey": false
            }
          ]
        },
        {
          "id": "pillar-8-8b-mcp-security-the-gap-almost-everyone-misses-k",
          "title": "8b · MCP security (the gap almost everyone misses) [KEY]",
          "items": [
            {
              "id": "p8-tool-poisoning-line-jumping-rug-pulls",
              "subtopic": "Tool poisoning, line jumping, rug pulls",
              "resourceName": "MCP Tool Poisoning — OWASP Foundation",
              "url": "https://owasp.org/www-community/attacks/MCP_Tool_Poisoning",
              "urlType": "read",
              "lengthLabel": "read",
              "lengthMinutes": null,
              "isKey": false
            },
            {
              "id": "p8-full-threat-model-defenses",
              "subtopic": "Full threat model + defenses",
              "resourceName": "MCP Security: Tool Poisoning threat model — Lens",
              "url": "https://lenshq.io/blog/mcp-security-tool-poisoning-threat-model/",
              "urlType": "read",
              "lengthLabel": "read",
              "lengthMinutes": null,
              "isKey": false
            },
            {
              "id": "p8-auth-credential-risk-cves",
              "subtopic": "Auth, credential risk, CVEs",
              "resourceName": "MCP Security Complete Guide — SentinelOne",
              "url": "https://www.sentinelone.com/cybersecurity-101/cybersecurity/mcp-security/",
              "urlType": "read",
              "lengthLabel": "read",
              "lengthMinutes": null,
              "isKey": false
            }
          ]
        }
      ],
      "callouts": [
        {
          "sectionId": "pillar-8-8b-mcp-security-the-gap-almost-everyone-misses-k",
          "text": "Gap fill — MCP security:: The MCP spec explicitly does NOT enforce security. A malicious server can hide instructions in tool descriptions/responses that your model trusts as developer instructions (tool poisoning) — a supply-chain-style attack, worse than normal prompt injection. Defenses: treat servers like pinned dependencies (version + content hash), default read-only, re-approve after changes, sandbox execution, validate tool responses before they hit the context."
        }
      ]
    },
    {
      "number": 9,
      "slugId": "pillar-9",
      "title": "Evals & Observability",
      "focus": "",
      "goal": "stop guess-and-tweak. Evaluation-driven development is the single biggest predictor of agent-building success (per Andrew Ng)",
      "sections": [
        {
          "id": "pillar-9",
          "title": "Core",
          "items": [
            {
              "id": "p9-objective-vs-llm-judge-error-analysis-traces",
              "subtopic": "Objective vs LLM-judge; error analysis; traces",
              "resourceName": "Agentic AI — Module 4 (Andrew Ng)",
              "url": "https://www.deeplearning.ai/courses/agentic-ai/",
              "urlType": "read",
              "lengthLabel": "in course",
              "lengthMinutes": null,
              "isKey": true
            },
            {
              "id": "p9-rag-evals-ragas-faithfulness-precision-recall",
              "subtopic": "RAG evals (RAGAS): faithfulness, precision, recall",
              "resourceName": "RAG Evaluation, RAGAS explained — Logical Lenses",
              "url": "https://www.youtube.com/watch?v=7_LTU0LA374",
              "urlType": "video",
              "lengthLabel": "12m",
              "lengthMinutes": 12,
              "isKey": false
            },
            {
              "id": "p9-ragas-in-code-run-in-ci",
              "subtopic": "RAGAS in code (run in CI)",
              "resourceName": "RAGAS Evaluation Tutorial (local, no API) — write-up",
              "url": "https://jheiduk.com/posts/ragas-evaluation-tutorial/",
              "urlType": "read",
              "lengthLabel": "read",
              "lengthMinutes": null,
              "isKey": false
            },
            {
              "id": "p9-tracing-observability-in-practice",
              "subtopic": "Tracing/observability in practice",
              "resourceName": "LangSmith docs",
              "url": "https://docs.langchain.com/langsmith/",
              "urlType": "doc",
              "lengthLabel": "docs",
              "lengthMinutes": null,
              "isKey": false
            }
          ]
        }
      ],
      "callouts": [
        {
          "sectionId": "pillar-9",
          "text": "Gap fill:: Traditional metrics (BLEU/ROUGE) don't work for RAG/agents — they measure wording, not grounding. Use RAGAS (no human labels needed) and treat it like unit tests in CI. For agents: prefer a rubric with a binary score per behavior over a vague 1–10 LLM-judge."
        }
      ]
    },
    {
      "number": 10,
      "slugId": "pillar-10",
      "title": "Security (Full OWASP Top-10 for LLM)",
      "focus": "",
      "goal": "know all ten risks, not just prompt injection. This is the biggest single-video gap — one injection video leaves 9 risks uncovered",
      "sections": [
        {
          "id": "pillar-10",
          "title": "Core",
          "items": [
            {
              "id": "p10-all-10-risks-in-4-minutes-overview",
              "subtopic": "All 10 risks in 4 minutes (overview)",
              "resourceName": "OWASP Top-10 for LLM 2025, full overview — Giskard",
              "url": "https://www.youtube.com/watch?v=j04st4edDKI",
              "urlType": "video",
              "lengthLabel": "4m",
              "lengthMinutes": 4,
              "isKey": true
            },
            {
              "id": "p10-llm01-prompt-injection-direct-indirect",
              "subtopic": "LLM01 Prompt Injection (direct/indirect)",
              "resourceName": "OWASP LLM01 explained — IT Bulls",
              "url": "https://www.youtube.com/watch?v=IvDCxdJRKRg",
              "urlType": "video",
              "lengthLabel": "25m",
              "lengthMinutes": 25,
              "isKey": false
            },
            {
              "id": "p10-deep-dive-w-real-exploits-fixes",
              "subtopic": "Deep dive w/ real exploits & fixes",
              "resourceName": "OWASP Top-10 for LLM deep dive — Ali Dorri",
              "url": "https://www.linkedin.com/posts/ali-dorri_deep-dive-into-owasp-top-10-for-large-language-activity-7336189972179230720-xkUX",
              "urlType": "read",
              "lengthLabel": "30m",
              "lengthMinutes": 30,
              "isKey": false
            },
            {
              "id": "p10-practitioner-guide-every-entry-controls",
              "subtopic": "Practitioner guide (every entry + controls)",
              "resourceName": "OWASP Top-10 for LLM — Practical Guide",
              "url": "https://maciejzalwert.medium.com/securing-llm-systems-a-practical-guide-to-the-owasp-top-10-c95453611374",
              "urlType": "read",
              "lengthLabel": "18m read",
              "lengthMinutes": 18,
              "isKey": false
            },
            {
              "id": "p10-full-defensive-course",
              "subtopic": "Full defensive course",
              "resourceName": "OWASP Top 10 for LLM Applications: AI Security Explained",
              "url": "https://www.udemy.com/courses/search/?q=owasp+top+10+llm+applications",
              "urlType": "course",
              "lengthLabel": "Udemy 13h",
              "lengthMinutes": 780,
              "isKey": false
            }
          ]
        }
      ],
      "callouts": [
        {
          "sectionId": "pillar-10",
          "text": "The 10 risks you must be able to name (LLM01–LLM10):"
        }
      ]
    }
  ],
  "sequence": [
    {
      "weeks": "---",
      "focus": "-------",
      "resources": "------- · -----------",
      "isKey": false
    },
    {
      "weeks": "☐",
      "focus": "1–2",
      "resources": "Foundations · Pillar 1 (transformers, 4 videos) + Pillar 2 start (Ed Donner Wks 1–2)",
      "isKey": false
    },
    {
      "weeks": "☐",
      "focus": "3–5",
      "resources": "RAG **[KEY]** · Pillar 3 all (build in Wk5) + Pillar 9 RAGAS",
      "isKey": false
    },
    {
      "weeks": "☐",
      "focus": "6",
      "resources": "Fine-tuning (optional) · Pillar 4 — skim unless a role needs it",
      "isKey": false
    },
    {
      "weeks": "☐",
      "focus": "7–8",
      "resources": "Agents + Context · Pillar 5 (Andrew Ng) + Pillar 6 (context/memory)",
      "isKey": false
    },
    {
      "weeks": "☐",
      "focus": "9–11",
      "resources": "Frameworks · Pillar 7 — ByteMonk → LangGraph → multi-agent",
      "isKey": false
    },
    {
      "weeks": "☐",
      "focus": "12–13",
      "resources": "MCP + Security · Pillar 8 (build + security) + Pillar 10 (OWASP Top-10)",
      "isKey": false
    },
    {
      "weeks": "☐",
      "focus": "14–17",
      "resources": "Build & Ship · Ed Donner Agentic AI Engineering — deploy 2–3 projects",
      "isKey": false
    }
  ],
  "portfolio": [
    {
      "id": "rag-knowledge-worker-with-hybrid-search-",
      "title": "RAG knowledge-worker with hybrid search + reranking + RAGAS scores"
    },
    {
      "id": "multi-agent-langgraph-system-with-memory",
      "title": "Multi-agent LangGraph system with memory + tracing"
    },
    {
      "id": "mcp-powered-agent-with-a-secured-server",
      "title": "MCP-powered agent (with a secured server)"
    },
    {
      "id": "a-deployed-career-digital-twin",
      "title": "A deployed Career Digital Twin"
    }
  ],
  "deliverableBar": "Clean READMEs (problem → approach → results → next) + a 2-min demo each. Deployed, demoable projects beat any certificate."
};
