// AUTO-GENERATED by scripts/build-roadmap.ts. Edit LLM_Agentic_AI_Roadmap_Tracker.md and regenerate.
import type { RoadmapData } from "./types";

export const ROADMAP: RoadmapData = {
  "pillars": [
    {
      "number": 1,
      "slugId": "pillar-1",
      "title": "Transformer & LLM Internals",
      "focus": "",
      "goal": "explain how an LLM works end-to-end without deep math. 3Blue1Brown chapters are the visual gold standard - watch in order",
      "sections": [
        {
          "id": "pillar-1",
          "title": "Core",
          "items": [
            {
              "id": "p1-big-picture-what-an-llm-is",
              "subtopic": "Big-picture: what an LLM is",
              "resourceName": "LLMs explained briefly - 3B1B (playlist)",
              "url": "https://www.youtube.com/watch?v=LPZh9BOjkQs",
              "urlType": "video",
              "lengthLabel": "8m",
              "lengthMinutes": 8,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "LLMs explained briefly - 3Blue1Brown (playlist)",
                  "url": null,
                  "urlType": "video",
                  "lengthLabel": "8m",
                  "lengthMinutes": 8
                },
                "free": {
                  "resourceName": "LLMs explained briefly - 3Blue1Brown (playlist)",
                  "url": null,
                  "urlType": "video",
                  "lengthLabel": "8m",
                  "lengthMinutes": 8
                }
              }
            },
            {
              "id": "p1-full-forward-pass-embeddings-softmax",
              "subtopic": "Full forward pass, embeddings, softmax",
              "resourceName": "Ch.5 Transformers, the tech behind LLMs - 3B1B",
              "url": "https://www.youtube.com/watch?v=wjZofJX0v4M",
              "urlType": "video",
              "lengthLabel": "27m",
              "lengthMinutes": 27,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "Ch.5 Transformers, the tech behind LLMs - 3B1B",
                  "url": "https://www.youtube.com/watch?v=wjZofJX0v4M",
                  "urlType": "video",
                  "lengthLabel": "27m",
                  "lengthMinutes": 27
                },
                "free": {
                  "resourceName": "Ch.5 Transformers, the tech behind LLMs - 3B1B",
                  "url": "https://www.youtube.com/watch?v=wjZofJX0v4M",
                  "urlType": "video",
                  "lengthLabel": "27m",
                  "lengthMinutes": 27
                }
              }
            },
            {
              "id": "p1-attention-q-k-v-masking-multi-head",
              "subtopic": "Attention: Q/K/V, masking, multi-head",
              "resourceName": "Ch.6 Attention, step-by-step - 3B1B",
              "url": "https://www.youtube.com/watch?v=eMlx5fFNoYc",
              "urlType": "video",
              "lengthLabel": "26m",
              "lengthMinutes": 26,
              "isKey": true,
              "alt": {
                "deep": {
                  "resourceName": "Ch.6 Attention, step-by-step - 3B1B",
                  "url": "https://www.youtube.com/watch?v=eMlx5fFNoYc",
                  "urlType": "video",
                  "lengthLabel": "26m",
                  "lengthMinutes": 26
                },
                "free": {
                  "resourceName": "Ch.6 Attention, step-by-step - 3B1B",
                  "url": "https://www.youtube.com/watch?v=eMlx5fFNoYc",
                  "urlType": "video",
                  "lengthLabel": "26m",
                  "lengthMinutes": 26
                }
              }
            },
            {
              "id": "p1-how-facts-live-in-mlp-layers-often-skipped",
              "subtopic": "How facts live in MLP layers (often skipped)",
              "resourceName": "Ch.7 How might LLMs store facts - 3B1B",
              "url": "https://www.youtube.com/watch?v=9-Jl0dxWQs8",
              "urlType": "video",
              "lengthLabel": "23m",
              "lengthMinutes": 23,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "Ch.7 How might LLMs store facts - 3B1B",
                  "url": "https://www.youtube.com/watch?v=9-Jl0dxWQs8",
                  "urlType": "video",
                  "lengthLabel": "23m",
                  "lengthMinutes": 23
                },
                "free": {
                  "resourceName": "Ch.7 How might LLMs store facts - 3B1B",
                  "url": "https://www.youtube.com/watch?v=9-Jl0dxWQs8",
                  "urlType": "video",
                  "lengthLabel": "23m",
                  "lengthMinutes": 23
                }
              }
            },
            {
              "id": "p1-tokenization-bpe-positional-encoding",
              "subtopic": "Tokenization/BPE + positional encoding",
              "resourceName": "Let's build GPT from scratch - Karpathy",
              "url": "https://www.youtube.com/watch?v=kCc8FmEb1nY",
              "urlType": "video",
              "lengthLabel": "1h56m",
              "lengthMinutes": 116,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "Let's build GPT from scratch - Karpathy",
                  "url": "https://www.youtube.com/watch?v=kCc8FmEb1nY",
                  "urlType": "video",
                  "lengthLabel": "1h56m",
                  "lengthMinutes": 116
                },
                "free": {
                  "resourceName": "Let's build GPT from scratch - Karpathy (YouTube)",
                  "url": null,
                  "urlType": "video",
                  "lengthLabel": "1h56m",
                  "lengthMinutes": 116
                }
              }
            }
          ]
        }
      ],
      "callouts": [
        {
          "sectionId": "pillar-1",
          "text": "Gap fill:: Most people only watch the attention video and miss (1) positional encoding - why order must be injected (Karpathy's build-GPT), (2) MLP/feed-forward layers store factual knowledge (3B1B Ch.7). Add both. Skip 3B1B Ch.1-4 (neural-net basics/backprop) unless you want them - not needed to build."
        }
      ],
      "extras": {
        "deep": [
          {
            "sectionTitle": "Extras",
            "items": [
              {
                "id": "d1-backprop-from-scratch-micrograd-key",
                "subtopic": "Backprop from scratch (micrograd) [KEY]",
                "resourceName": "Neural Networks: Zero to Hero, Ep.1 - Karpathy",
                "url": null,
                "urlType": "video",
                "lengthLabel": "2h25m",
                "lengthMinutes": 145,
                "isKey": false
              },
              {
                "id": "d1-building-an-mlp-language-model-makemore-pt-1-2",
                "subtopic": "Building an MLP language model (makemore pt.1-2)",
                "resourceName": "Neural Networks: Zero to Hero, Ep.2-3 - Karpathy",
                "url": null,
                "urlType": "video",
                "lengthLabel": "~2h30m",
                "lengthMinutes": 150,
                "isKey": false
              },
              {
                "id": "d1-why-training-breaks-activations-gradients-batchn",
                "subtopic": "Why training breaks: activations, gradients, batchnorm",
                "resourceName": "Neural Networks: Zero to Hero, Ep.4 - Karpathy",
                "url": null,
                "urlType": "video",
                "lengthLabel": "1h55m",
                "lengthMinutes": 115,
                "isKey": false
              },
              {
                "id": "d1-loss-functions-gradient-descent-in-plain-languag",
                "subtopic": "Loss functions & gradient descent, in plain language",
                "resourceName": "But what is a neural network? - 3Blue1Brown Ch.1-2",
                "url": null,
                "urlType": "video",
                "lengthLabel": "~40m",
                "lengthMinutes": 40,
                "isKey": false
              },
              {
                "id": "d1-cnns-rnns-the-1-video-version-context-only",
                "subtopic": "CNNs & RNNs - the 1-video version (context only)",
                "resourceName": "CNNs and RNNs explained simply - any solid overview",
                "url": null,
                "urlType": "video",
                "lengthLabel": "~20m",
                "lengthMinutes": 20,
                "isKey": false
              }
            ]
          }
        ],
        "free": [
          {
            "sectionTitle": "Extras",
            "items": [
              {
                "id": "f1-backprop-from-scratch-micrograd-key",
                "subtopic": "Backprop from scratch (micrograd) [KEY]",
                "resourceName": "Neural Networks: Zero to Hero, Ep.1 - Karpathy (YouTube)",
                "url": null,
                "urlType": "video",
                "lengthLabel": "2h25m",
                "lengthMinutes": 145,
                "isKey": false
              },
              {
                "id": "f1-building-an-mlp-language-model-makemore-pt-1-2",
                "subtopic": "Building an MLP language model (makemore pt.1-2)",
                "resourceName": "Neural Networks: Zero to Hero, Ep.2-3 - Karpathy",
                "url": null,
                "urlType": "video",
                "lengthLabel": "~2h30m",
                "lengthMinutes": 150,
                "isKey": false
              },
              {
                "id": "f1-why-training-breaks-activations-gradients-batchn",
                "subtopic": "Why training breaks: activations, gradients, batchnorm",
                "resourceName": "Neural Networks: Zero to Hero, Ep.4 - Karpathy",
                "url": null,
                "urlType": "video",
                "lengthLabel": "1h55m",
                "lengthMinutes": 115,
                "isKey": false
              },
              {
                "id": "f1-loss-functions-gradient-descent-in-plain-languag",
                "subtopic": "Loss functions & gradient descent, in plain language",
                "resourceName": "But what is a neural network? - 3Blue1Brown Ch.1-2",
                "url": null,
                "urlType": "video",
                "lengthLabel": "~40m",
                "lengthMinutes": 40,
                "isKey": false
              },
              {
                "id": "f1-cnns-rnns-the-1-video-version-context-only",
                "subtopic": "CNNs & RNNs - the 1-video version (context only)",
                "resourceName": "CNNs and RNNs explained simply - any solid free YouTube overview",
                "url": null,
                "urlType": "video",
                "lengthLabel": "~20m",
                "lengthMinutes": 20,
                "isKey": false
              }
            ]
          }
        ]
      }
    },
    {
      "number": 2,
      "slugId": "pillar-2",
      "title": "LLM App Fundamentals",
      "focus": "",
      "goal": "go from \"I can call an API\" to \"I can ship an LLM feature.\" Ed Donner's course (Ollama-first, laptop-friendly) is strongest here",
      "sections": [
        {
          "id": "pillar-2",
          "title": "Core",
          "items": [
            {
              "id": "p2-apis-prompts-streaming-multi-provider",
              "subtopic": "APIs, prompts, streaming, multi-provider",
              "resourceName": "Ed Donner - LLM Engineering, Wks 1-2 (repo)",
              "url": "https://github.com/ed-donner/llm_engineering",
              "urlType": "repo",
              "lengthLabel": "Udemy",
              "lengthMinutes": null,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "Ed Donner - LLM Engineering, Wks 1-2 (repo)",
                  "url": "https://github.com/ed-donner/llm_engineering",
                  "urlType": "repo",
                  "lengthLabel": "Udemy",
                  "lengthMinutes": null
                },
                "free": {
                  "resourceName": "Building Systems with the ChatGPT API - DeepLearning.AI",
                  "url": null,
                  "urlType": "video",
                  "lengthLabel": "~1h",
                  "lengthMinutes": 60
                }
              }
            },
            {
              "id": "p2-tool-function-calling",
              "subtopic": "Tool / function calling",
              "resourceName": "Ed Donner Wk2 + ReAct explainer",
              "url": "https://www.udemy.com/courses/search/?q=llm+engineering+ed+donner",
              "urlType": "course",
              "lengthLabel": "Udemy+6m",
              "lengthMinutes": 6,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "Ed Donner Wk2 + ReAct explainer",
                  "url": "https://www.udemy.com/courses/search/?q=llm+engineering+ed+donner",
                  "urlType": "course",
                  "lengthLabel": "Udemy+6m",
                  "lengthMinutes": 6
                },
                "free": {
                  "resourceName": "Function-calling and data extraction with LLMs - DeepLearning.AI + 🟢 OpenAI Cookbook: function calling",
                  "url": null,
                  "urlType": "read",
                  "lengthLabel": "~1h + read",
                  "lengthMinutes": 60
                }
              }
            },
            {
              "id": "p2-fast-uis-gradio",
              "subtopic": "Fast UIs (Gradio)",
              "resourceName": "Ed Donner Wk2",
              "url": "https://www.udemy.com/courses/search/?q=llm+engineering+ed+donner",
              "urlType": "course",
              "lengthLabel": "Udemy",
              "lengthMinutes": null,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "Ed Donner Wk2",
                  "url": "https://www.udemy.com/courses/search/?q=llm+engineering+ed+donner",
                  "urlType": "course",
                  "lengthLabel": "Udemy",
                  "lengthMinutes": null
                },
                "free": {
                  "resourceName": "Building Generative AI Applications with Gradio - DeepLearning.AI (or 🟢 Gradio official Quickstart docs)",
                  "url": null,
                  "urlType": "doc",
                  "lengthLabel": "~1h",
                  "lengthMinutes": 60
                }
              }
            },
            {
              "id": "p2-open-source-models-huggingface",
              "subtopic": "Open-source models & HuggingFace",
              "resourceName": "Ed Donner Wk3",
              "url": "https://www.udemy.com/courses/search/?q=llm+engineering+ed+donner",
              "urlType": "course",
              "lengthLabel": "Udemy",
              "lengthMinutes": null,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "Ed Donner Wk3",
                  "url": "https://www.udemy.com/courses/search/?q=llm+engineering+ed+donner",
                  "urlType": "course",
                  "lengthLabel": "Udemy",
                  "lengthMinutes": null
                },
                "free": {
                  "resourceName": "Open Source Models with Hugging Face - DeepLearning.AI + 🟢 HuggingFace NLP Course Ch.1-2",
                  "url": null,
                  "urlType": "video",
                  "lengthLabel": "~1h + 3h",
                  "lengthMinutes": 60
                }
              }
            },
            {
              "id": "p2-model-selection-leaderboards",
              "subtopic": "Model selection / leaderboards",
              "resourceName": "Ed Donner Wk4",
              "url": "https://www.udemy.com/courses/search/?q=llm+engineering+ed+donner",
              "urlType": "course",
              "lengthLabel": "Udemy",
              "lengthMinutes": null,
              "isKey": false,
              "alt": {
                "free": {
                  "resourceName": "Hugging Face Open LLM Leaderboard (read) + provider pricing pages",
                  "url": null,
                  "urlType": "read",
                  "lengthLabel": "read",
                  "lengthMinutes": null
                }
              }
            },
            {
              "id": "p2-structured-output-json-pydantic",
              "subtopic": "Structured output (JSON/Pydantic)",
              "resourceName": "Structured outputs - OpenAI docs",
              "url": "https://developers.openai.com/api/docs/guides/structured-outputs",
              "urlType": "doc",
              "lengthLabel": "read",
              "lengthMinutes": null,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "Structured outputs - OpenAI docs",
                  "url": "https://developers.openai.com/api/docs/guides/structured-outputs",
                  "urlType": "doc",
                  "lengthLabel": "read",
                  "lengthMinutes": null
                },
                "free": {
                  "resourceName": "Structured outputs - OpenAI docs",
                  "url": "https://developers.openai.com/api/docs/guides/structured-outputs",
                  "urlType": "doc",
                  "lengthLabel": "read",
                  "lengthMinutes": null
                }
              }
            }
          ]
        }
      ],
      "callouts": [],
      "extras": {
        "deep": [
          {
            "sectionTitle": "Extras",
            "items": [
              {
                "id": "d2-prompt-engineering-patterns-few-shot-cot-system",
                "subtopic": "Prompt engineering patterns (few-shot, CoT, system prompts)",
                "resourceName": "Prompt Engineering Guide - promptingguide.ai",
                "url": null,
                "urlType": "read",
                "lengthLabel": "read 1h",
                "lengthMinutes": 60,
                "isKey": false
              },
              {
                "id": "d2-model-selection-leaderboards-cost-latency-trade",
                "subtopic": "Model selection / leaderboards / cost-latency trade-offs",
                "resourceName": "Ed Donner Wk4",
                "url": "https://www.udemy.com/courses/search/?q=llm+engineering+ed+donner",
                "urlType": "course",
                "lengthLabel": "Udemy",
                "lengthMinutes": null,
                "isKey": false
              }
            ]
          }
        ],
        "free": [
          {
            "sectionTitle": "Extras",
            "items": [
              {
                "id": "f2-prompt-engineering-patterns-few-shot-cot-system",
                "subtopic": "Prompt engineering patterns (few-shot, CoT, system prompts)",
                "resourceName": "ChatGPT Prompt Engineering for Developers - DeepLearning.AI + 🟢 promptingguide.ai (read)",
                "url": null,
                "urlType": "read",
                "lengthLabel": "~1h + 1h read",
                "lengthMinutes": 60,
                "isKey": false
              }
            ]
          }
        ]
      }
    },
    {
      "number": 3,
      "slugId": "pillar-3",
      "title": "RAG (Basic → Advanced → Eval)",
      "focus": "",
      "goal": "build RAG that works in production. Biggest hidden gap - basic tutorials stop at \"embed + top-k,\" real systems need hybrid search, reranking, evaluation",
      "sections": [
        {
          "id": "pillar-3-3a-foundations",
          "title": "3a · Foundations",
          "items": [
            {
              "id": "p3-why-rag-embeddings-vector-db-cosine",
              "subtopic": "Why RAG; embeddings; vector DB; cosine",
              "resourceName": "RAG from First Principles - Ankit Bansal",
              "url": null,
              "urlType": "unverified",
              "lengthLabel": "38m",
              "lengthMinutes": 38,
              "isKey": true,
              "alt": {
                "deep": {
                  "resourceName": "RAG from First Principles - Ankit Bansal",
                  "url": null,
                  "urlType": "video",
                  "lengthLabel": "38m",
                  "lengthMinutes": 38
                },
                "free": {
                  "resourceName": "RAG from First Principles - Ankit Bansal (YouTube)",
                  "url": null,
                  "urlType": "video",
                  "lengthLabel": "38m",
                  "lengthMinutes": 38
                }
              }
            },
            {
              "id": "p3-build-a-real-rag-app",
              "subtopic": "Build a real RAG app",
              "resourceName": "Ed Donner - LLM Engineering, Wk5 (knowledge-worker)",
              "url": "https://github.com/ed-donner/llm_engineering",
              "urlType": "repo",
              "lengthLabel": "Udemy",
              "lengthMinutes": null,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "Ed Donner - LLM Engineering, Wk5 (knowledge-worker)",
                  "url": "https://github.com/ed-donner/llm_engineering",
                  "urlType": "repo",
                  "lengthLabel": "Udemy",
                  "lengthMinutes": null
                },
                "free": {
                  "resourceName": "LangChain: Chat with Your Data - DeepLearning.AI",
                  "url": null,
                  "urlType": "video",
                  "lengthLabel": "~1.5h",
                  "lengthMinutes": 90
                }
              }
            }
          ]
        },
        {
          "id": "pillar-3-3b-advanced-retrieval-the-gap",
          "title": "3b · Advanced retrieval (the gap)",
          "items": [
            {
              "id": "p3-hybrid-search-bm25-dense-rrf",
              "subtopic": "Hybrid search: BM25 + dense + RRF",
              "resourceName": "Production RAG w/ LangChain & Vector DBs - freeCodeCamp",
              "url": "https://www.youtube.com/watch?v=mHxLXzYjQRE",
              "urlType": "video",
              "lengthLabel": "7h38m",
              "lengthMinutes": 458,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "Production RAG w/ LangChain & Vector DBs - freeCodeCamp",
                  "url": "https://www.youtube.com/watch?v=mHxLXzYjQRE",
                  "urlType": "video",
                  "lengthLabel": "7h38m",
                  "lengthMinutes": 458
                },
                "free": {
                  "resourceName": "Production RAG w/ LangChain & Vector DBs - freeCodeCamp",
                  "url": "https://www.youtube.com/watch?v=mHxLXzYjQRE",
                  "urlType": "video",
                  "lengthLabel": "7h38m",
                  "lengthMinutes": 458
                }
              }
            },
            {
              "id": "p3-reranking-cross-encoders-colbert",
              "subtopic": "Reranking (cross-encoders/ColBERT)",
              "resourceName": "Advanced RAG techniques - Field Guide to AI",
              "url": "https://fieldguidetoai.com/guides/advanced-rag-techniques",
              "urlType": "read",
              "lengthLabel": "9m read",
              "lengthMinutes": 9,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "Advanced RAG techniques - Field Guide to AI",
                  "url": "https://fieldguidetoai.com/guides/advanced-rag-techniques",
                  "urlType": "read",
                  "lengthLabel": "9m read",
                  "lengthMinutes": 9
                },
                "free": {
                  "resourceName": "Advanced RAG techniques - Field Guide to AI",
                  "url": "https://fieldguidetoai.com/guides/advanced-rag-techniques",
                  "urlType": "read",
                  "lengthLabel": "9m read",
                  "lengthMinutes": 9
                }
              }
            },
            {
              "id": "p3-query-transforms-hyde-multi-query",
              "subtopic": "Query transforms (HyDE, multi-query)",
              "resourceName": "Advanced RAG: hybrid, reranking, query expansion",
              "url": "https://reynaldineo.com/blog/exploring-advance-retrieval-techniques",
              "urlType": "read",
              "lengthLabel": "read",
              "lengthMinutes": null,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "Advanced RAG: hybrid, reranking, query expansion",
                  "url": "https://reynaldineo.com/blog/exploring-advance-retrieval-techniques",
                  "urlType": "read",
                  "lengthLabel": "read",
                  "lengthMinutes": null
                },
                "free": {
                  "resourceName": "Advanced RAG: hybrid, reranking, query expansion (read)",
                  "url": null,
                  "urlType": "read",
                  "lengthLabel": "read",
                  "lengthMinutes": null
                }
              }
            },
            {
              "id": "p3-chunking-parent-child-sentence-window",
              "subtopic": "Chunking: parent-child, sentence-window",
              "resourceName": "12 Advanced RAG Techniques (2026) - Atlan",
              "url": "https://atlan.com/know/advanced-rag-techniques/",
              "urlType": "read",
              "lengthLabel": "read",
              "lengthMinutes": null,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "12 Advanced RAG Techniques (2026) - Atlan",
                  "url": "https://atlan.com/know/advanced-rag-techniques/",
                  "urlType": "read",
                  "lengthLabel": "read",
                  "lengthMinutes": null
                },
                "free": {
                  "resourceName": "12 Advanced RAG Techniques (2026) - Atlan",
                  "url": "https://atlan.com/know/advanced-rag-techniques/",
                  "urlType": "read",
                  "lengthLabel": "read",
                  "lengthMinutes": null
                }
              }
            },
            {
              "id": "p3-graphrag-raptor-contextual-retrieval",
              "subtopic": "GraphRAG / RAPTOR / Contextual Retrieval",
              "resourceName": "Same Atlan guide (techniques 8-12)",
              "url": "https://atlan.com/know/advanced-rag-techniques/",
              "urlType": "read",
              "lengthLabel": "read",
              "lengthMinutes": null,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "Same Atlan guide (techniques 8-12)",
                  "url": "https://atlan.com/know/advanced-rag-techniques/",
                  "urlType": "read",
                  "lengthLabel": "read",
                  "lengthMinutes": null
                },
                "free": {
                  "resourceName": "Same Atlan guide (techniques 8-12)",
                  "url": "https://atlan.com/know/advanced-rag-techniques/",
                  "urlType": "read",
                  "lengthLabel": "read",
                  "lengthMinutes": null
                }
              }
            }
          ]
        },
        {
          "id": "pillar-3-3c-rag-evaluation-ragas-key",
          "title": "3c · RAG evaluation (RAGAS) [KEY]",
          "items": [
            {
              "id": "p3-metrics-faithfulness-context-precision-recall",
              "subtopic": "Metrics: faithfulness, context precision/recall",
              "resourceName": "RAG Evaluation, RAGAS explained - Logical Lenses",
              "url": "https://www.youtube.com/watch?v=7_LTU0LA374",
              "urlType": "video",
              "lengthLabel": "12m",
              "lengthMinutes": 12,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "RAG Evaluation, RAGAS explained - Logical Lenses",
                  "url": "https://www.youtube.com/watch?v=7_LTU0LA374",
                  "urlType": "video",
                  "lengthLabel": "12m",
                  "lengthMinutes": 12
                },
                "free": {
                  "resourceName": "RAG Evaluation, RAGAS explained - Logical Lenses",
                  "url": "https://www.youtube.com/watch?v=7_LTU0LA374",
                  "urlType": "video",
                  "lengthLabel": "12m",
                  "lengthMinutes": 12
                }
              }
            },
            {
              "id": "p3-ragas-hands-on-in-python",
              "subtopic": "RAGAS hands-on in Python",
              "resourceName": "RAG Evaluation Metrics Tutorial - Analytics Vidhya",
              "url": "https://www.analyticsvidhya.com/blog/2024/05/a-beginners-guide-to-evaluating-rag-pipelines-using-ragas/",
              "urlType": "read",
              "lengthLabel": "6m",
              "lengthMinutes": 6,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "RAG Evaluation Metrics Tutorial - Analytics Vidhya",
                  "url": "https://www.analyticsvidhya.com/blog/2024/05/a-beginners-guide-to-evaluating-rag-pipelines-using-ragas/",
                  "urlType": "video",
                  "lengthLabel": "6m",
                  "lengthMinutes": 6
                },
                "free": {
                  "resourceName": "RAG Evaluation Metrics Tutorial - Analytics Vidhya",
                  "url": "https://www.analyticsvidhya.com/blog/2024/05/a-beginners-guide-to-evaluating-rag-pipelines-using-ragas/",
                  "urlType": "video",
                  "lengthLabel": "6m",
                  "lengthMinutes": 6
                }
              }
            }
          ]
        }
      ],
      "callouts": [
        {
          "sectionId": "pillar-3-3c-rag-evaluation-ragas-key",
          "text": "Gap fill:: Basic RAG scores ~44% factual accuracy; adding hybrid search + reranking pushes it toward ~63% (CRAG benchmark). Do NOT ship RAG without: (1) a reranker, (2) hybrid (BM25+dense) retrieval, (3) a RAGAS eval harness run in CI on every change. Rule of thumb: measure retrieval quality (context precision/recall) separately from generation quality (faithfulness)."
        }
      ],
      "extras": {
        "free": [
          {
            "sectionTitle": "4b · Advanced retrieval (the gap most courses skip)",
            "items": [
              {
                "id": "f3-advanced-rag-applications-end-to-end",
                "subtopic": "Advanced RAG applications, end-to-end",
                "resourceName": "Building and Evaluating Advanced RAG Applications - DeepLearning.AI",
                "url": null,
                "urlType": "video",
                "lengthLabel": "~1.5h",
                "lengthMinutes": 90,
                "isKey": false
              }
            ]
          }
        ]
      }
    },
    {
      "number": 4,
      "slugId": "pillar-4",
      "title": "Fine-Tuning (LoRA/QLoRA)",
      "focus": "",
      "goal": "know when NOT to fine-tune, and how LoRA/QLoRA make it cheap. Optional for most app work - but a common interview topic",
      "sections": [
        {
          "id": "pillar-4",
          "title": "Core",
          "items": [
            {
              "id": "p4-the-one-rule-fine-tune-behavior-not-knowledge",
              "subtopic": "The one rule: fine-tune = behavior, not knowledge",
              "resourceName": "How to Fine-Tune an LLM (2026) - read intro",
              "url": "https://www.layer3labs.io/guides/how-to-fine-tune-an-llm",
              "urlType": "read",
              "lengthLabel": "read",
              "lengthMinutes": null,
              "isKey": true,
              "alt": {
                "deep": {
                  "resourceName": "How to Fine-Tune an LLM (2026) - read intro",
                  "url": "https://www.layer3labs.io/guides/how-to-fine-tune-an-llm",
                  "urlType": "read",
                  "lengthLabel": "read",
                  "lengthMinutes": null
                },
                "free": {
                  "resourceName": "How to Fine-Tune an LLM (2026) - read intro",
                  "url": "https://www.layer3labs.io/guides/how-to-fine-tune-an-llm",
                  "urlType": "read",
                  "lengthLabel": "read",
                  "lengthMinutes": null
                }
              }
            },
            {
              "id": "p4-lora-qlora-rank-alpha-dropout-4-bit-nf4",
              "subtopic": "LoRA/QLoRA + rank, alpha, dropout, 4-bit NF4",
              "resourceName": "LoRA & QLoRA In-Depth - Mark Hennings",
              "url": "https://www.youtube.com/watch?v=t1caDsMzWBk",
              "urlType": "video",
              "lengthLabel": "15m",
              "lengthMinutes": 15,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "LoRA & QLoRA In-Depth - Mark Hennings",
                  "url": "https://www.youtube.com/watch?v=t1caDsMzWBk",
                  "urlType": "video",
                  "lengthLabel": "15m",
                  "lengthMinutes": 15
                },
                "free": {
                  "resourceName": "LoRA & QLoRA In-Depth - Mark Hennings",
                  "url": "https://www.youtube.com/watch?v=t1caDsMzWBk",
                  "urlType": "video",
                  "lengthLabel": "15m",
                  "lengthMinutes": 15
                }
              }
            },
            {
              "id": "p4-quick-peft-overview-lora-qlora-dora",
              "subtopic": "Quick PEFT overview (LoRA/QLoRA/DoRA)",
              "resourceName": "PEFT Explained - Arivu",
              "url": null,
              "urlType": "unverified",
              "lengthLabel": "4m",
              "lengthMinutes": 4,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "PEFT Explained - Arivu",
                  "url": null,
                  "urlType": "video",
                  "lengthLabel": "4m",
                  "lengthMinutes": 4
                },
                "free": {
                  "resourceName": "PEFT Explained - Arivu",
                  "url": null,
                  "urlType": "video",
                  "lengthLabel": "4m",
                  "lengthMinutes": 4
                }
              }
            },
            {
              "id": "p4-end-to-end-deep-dive-code",
              "subtopic": "End-to-end deep dive + code",
              "resourceName": "LoRA & QLoRA Explained Simply - Sunny Savita",
              "url": "https://www.youtube.com/watch?v=cO6Ly7mIziQ",
              "urlType": "video",
              "lengthLabel": "1h27m",
              "lengthMinutes": 87,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "LoRA & QLoRA Explained Simply - Sunny Savita",
                  "url": "https://www.youtube.com/watch?v=cO6Ly7mIziQ",
                  "urlType": "video",
                  "lengthLabel": "1h27m",
                  "lengthMinutes": 87
                },
                "free": {
                  "resourceName": "LoRA & QLoRA Explained Simply - Sunny Savita",
                  "url": "https://www.youtube.com/watch?v=cO6Ly7mIziQ",
                  "urlType": "video",
                  "lengthLabel": "1h27m",
                  "lengthMinutes": 87
                }
              }
            },
            {
              "id": "p4-fine-tune-in-the-course",
              "subtopic": "Fine-tune in the course",
              "resourceName": "Ed Donner - LLM Engineering, Wks 6-7",
              "url": "https://www.udemy.com/courses/search/?q=llm+engineering+ed+donner",
              "urlType": "course",
              "lengthLabel": "Udemy",
              "lengthMinutes": null,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "Ed Donner - LLM Engineering, Wks 6-7",
                  "url": "https://www.udemy.com/courses/search/?q=llm+engineering+ed+donner",
                  "urlType": "course",
                  "lengthLabel": "Udemy",
                  "lengthMinutes": null
                }
              }
            }
          ]
        }
      ],
      "callouts": [
        {
          "sectionId": "pillar-4",
          "text": "Gap fill:: Interviewers love \"RAG vs fine-tuning?\" - RAG for fresh/changing facts & citations; fine-tuning for format, tone, domain vocabulary, reasoning style. Never fine-tune to \"teach it your documents.\" Know QLoRA specifics: 4-bit NF4 quantization of the frozen base + small trainable low-rank adapters on the attention projections."
        }
      ],
      "extras": {
        "free": [
          {
            "sectionTitle": "Extras",
            "items": [
              {
                "id": "f4-concept-overview-when-why-to-fine-tune",
                "subtopic": "Concept overview, when/why to fine-tune",
                "resourceName": "Finetuning Large Language Models - DeepLearning.AI",
                "url": null,
                "urlType": "video",
                "lengthLabel": "~1h",
                "lengthMinutes": 60,
                "isKey": false
              },
              {
                "id": "f4-hands-on-fine-tune-with-hugging-face-peft",
                "subtopic": "Hands-on: fine-tune with Hugging Face PEFT",
                "resourceName": "Hugging Face PEFT docs & fine-tuning tutorial",
                "url": null,
                "urlType": "doc",
                "lengthLabel": "read + code-along",
                "lengthMinutes": null,
                "isKey": false
              }
            ]
          }
        ]
      }
    },
    {
      "number": 5,
      "slugId": "pillar-5",
      "title": "Agents & Design Patterns",
      "focus": "",
      "goal": "understand agents from first principles (vendor-neutral) before frameworks. Andrew Ng's course is the backbone",
      "sections": [
        {
          "id": "pillar-5",
          "title": "Core",
          "items": [
            {
              "id": "p5-agent-vs-workflow-react-loop",
              "subtopic": "Agent vs workflow; ReAct loop",
              "resourceName": "AI Agents, Clearly Explained - Jeff Su",
              "url": "https://www.youtube.com/watch?v=FwOTs4UxQS4",
              "urlType": "video",
              "lengthLabel": "10m",
              "lengthMinutes": 10,
              "isKey": true,
              "alt": {
                "deep": {
                  "resourceName": "AI Agents, Clearly Explained - Jeff Su",
                  "url": "https://www.youtube.com/watch?v=FwOTs4UxQS4",
                  "urlType": "video",
                  "lengthLabel": "10m",
                  "lengthMinutes": 10
                },
                "free": {
                  "resourceName": "AI Agents, Clearly Explained - Jeff Su",
                  "url": "https://www.youtube.com/watch?v=FwOTs4UxQS4",
                  "urlType": "video",
                  "lengthLabel": "10m",
                  "lengthMinutes": 10
                }
              }
            },
            {
              "id": "p5-react-in-practice",
              "subtopic": "ReAct in practice",
              "resourceName": "ReAct Agents, clearly explained - Akshay Pachaar",
              "url": "https://www.youtube.com/watch?v=vFdIrZyKEwQ",
              "urlType": "video",
              "lengthLabel": "6m",
              "lengthMinutes": 6,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "ReAct Agents, clearly explained - Akshay Pachaar",
                  "url": "https://www.youtube.com/watch?v=vFdIrZyKEwQ",
                  "urlType": "video",
                  "lengthLabel": "6m",
                  "lengthMinutes": 6
                },
                "free": {
                  "resourceName": "ReAct Agents, clearly explained - Akshay Pachaar",
                  "url": "https://www.youtube.com/watch?v=vFdIrZyKEwQ",
                  "urlType": "video",
                  "lengthLabel": "6m",
                  "lengthMinutes": 6
                }
              }
            },
            {
              "id": "p5-4-patterns-evals-whole-course",
              "subtopic": "4 patterns + evals (whole course)",
              "resourceName": "Agentic AI - Andrew Ng, DeepLearning.AI",
              "url": "https://www.deeplearning.ai/courses/agentic-ai/",
              "urlType": "read",
              "lengthLabel": "7h45m",
              "lengthMinutes": 465,
              "isKey": true,
              "alt": {
                "deep": {
                  "resourceName": "Agentic AI - Andrew Ng, DeepLearning.AI",
                  "url": "https://www.deeplearning.ai/courses/agentic-ai/",
                  "urlType": "video",
                  "lengthLabel": "7h45m",
                  "lengthMinutes": 465
                },
                "free": {
                  "resourceName": "Agentic AI - Andrew Ng, DeepLearning.AI",
                  "url": "https://www.deeplearning.ai/courses/agentic-ai/",
                  "urlType": "video",
                  "lengthLabel": "7h45m",
                  "lengthMinutes": 465
                }
              }
            },
            {
              "id": "p5-reflection-tool-use-planning-multi-agent",
              "subtopic": "Reflection / Tool use / Planning / Multi-agent",
              "resourceName": "Same course, Modules 2/3/1/5 · notes repo",
              "url": "https://github.com/rczhen/agentic-ai-course-notes",
              "urlType": "repo",
              "lengthLabel": "incl.",
              "lengthMinutes": null,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "Same course, Modules 2/3/1/5 · notes repo",
                  "url": "https://github.com/rczhen/agentic-ai-course-notes",
                  "urlType": "repo",
                  "lengthLabel": "incl.",
                  "lengthMinutes": null
                },
                "free": {
                  "resourceName": "Same course, Modules 2/3/1/5 · 🟢 notes repo",
                  "url": null,
                  "urlType": "repo",
                  "lengthLabel": "incl.",
                  "lengthMinutes": null
                }
              }
            },
            {
              "id": "p5-build-8-agent-projects",
              "subtopic": "Build 8 agent projects",
              "resourceName": "Ed Donner - Agentic AI Engineering (repo)",
              "url": "https://github.com/ed-donner/agents",
              "urlType": "repo",
              "lengthLabel": "Udemy",
              "lengthMinutes": null,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "Ed Donner - Agentic AI Engineering (repo)",
                  "url": "https://github.com/ed-donner/agents",
                  "urlType": "repo",
                  "lengthLabel": "Udemy",
                  "lengthMinutes": null
                },
                "free": {
                  "resourceName": "AI Agents in LangGraph - DeepLearning.AI + 🔵 Building Agentic RAG with LlamaIndex - DeepLearning.AI",
                  "url": null,
                  "urlType": "video",
                  "lengthLabel": "~2h + ~1.5h",
                  "lengthMinutes": 120
                }
              }
            }
          ]
        }
      ],
      "callouts": []
    },
    {
      "number": 6,
      "slugId": "pillar-6",
      "title": "Context Engineering & Memory",
      "focus": "",
      "goal": "the #1 skill for reliable agents in 2025-26, and almost always missing from course lists",
      "sections": [
        {
          "id": "pillar-6",
          "title": "Core",
          "items": [
            {
              "id": "p6-context-window-as-scarce-ram-write-select-compre",
              "subtopic": "Context window as scarce RAM; write/select/compress/isolate",
              "resourceName": "Context Engineering for Agents - LangChain",
              "url": "https://www.langchain.com/blog/context-engineering-for-agents",
              "urlType": "read",
              "lengthLabel": "14m read",
              "lengthMinutes": 14,
              "isKey": true,
              "alt": {
                "deep": {
                  "resourceName": "Context Engineering for Agents - LangChain",
                  "url": "https://www.langchain.com/blog/context-engineering-for-agents",
                  "urlType": "read",
                  "lengthLabel": "14m read",
                  "lengthMinutes": 14
                },
                "free": {
                  "resourceName": "Context Engineering for Agents - LangChain (blog)",
                  "url": null,
                  "urlType": "read",
                  "lengthLabel": "14m read",
                  "lengthMinutes": 14
                }
              }
            },
            {
              "id": "p6-anthropic-s-mental-model-failure-modes",
              "subtopic": "Anthropic's mental model + failure modes",
              "resourceName": "Effective context engineering - Anthropic",
              "url": "https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents",
              "urlType": "read",
              "lengthLabel": "read",
              "lengthMinutes": null,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "Effective context engineering - Anthropic",
                  "url": "https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents",
                  "urlType": "read",
                  "lengthLabel": "read",
                  "lengthMinutes": null
                },
                "free": {
                  "resourceName": "Effective context engineering - Anthropic (blog)",
                  "url": null,
                  "urlType": "read",
                  "lengthLabel": "read",
                  "lengthMinutes": null
                }
              }
            },
            {
              "id": "p6-short-vs-long-vs-episodic-memory",
              "subtopic": "Short vs long vs episodic memory",
              "resourceName": "Context Engineering: LLM Memory & Retrieval - Weaviate",
              "url": "https://weaviate.io/blog/context-engineering",
              "urlType": "read",
              "lengthLabel": "22m read",
              "lengthMinutes": 22,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "Context Engineering: LLM Memory & Retrieval - Weaviate",
                  "url": "https://weaviate.io/blog/context-engineering",
                  "urlType": "read",
                  "lengthLabel": "22m read",
                  "lengthMinutes": 22
                },
                "free": {
                  "resourceName": "Context Engineering: LLM Memory & Retrieval - Weaviate",
                  "url": "https://weaviate.io/blog/context-engineering",
                  "urlType": "read",
                  "lengthLabel": "22m read",
                  "lengthMinutes": 22
                }
              }
            },
            {
              "id": "p6-memory-taxonomy-tools-mem0-letta-zep",
              "subtopic": "Memory taxonomy + tools (Mem0, Letta, Zep)",
              "resourceName": "AI Agent Memory Explained - three layers",
              "url": "https://machinelearningmastery.com/ai-agent-memory-explained-in-3-levels-of-difficulty/",
              "urlType": "read",
              "lengthLabel": "8m read",
              "lengthMinutes": 8,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "AI Agent Memory Explained - three layers",
                  "url": "https://machinelearningmastery.com/ai-agent-memory-explained-in-3-levels-of-difficulty/",
                  "urlType": "read",
                  "lengthLabel": "8m read",
                  "lengthMinutes": 8
                },
                "free": {
                  "resourceName": "AI Agent Memory Explained - three layers",
                  "url": "https://machinelearningmastery.com/ai-agent-memory-explained-in-3-levels-of-difficulty/",
                  "urlType": "read",
                  "lengthLabel": "8m read",
                  "lengthMinutes": 8
                }
              }
            }
          ]
        }
      ],
      "callouts": [
        {
          "sectionId": "pillar-6",
          "text": "Gap fill - why this matters:: Cognition & Anthropic both call context engineering \"the #1 job of engineers building agents.\" Long runs cause context poisoning, distraction, confusion, and clash. Learn the four moves: write (persist), select (retrieve), compress (summarize/truncate), isolate (sub-agents). Memory = engineering you add: short-term (context window), long-term (vector store), episodic (log of past runs). Most production bugs live in the handoffs between these layers."
        }
      ]
    },
    {
      "number": 7,
      "slugId": "pillar-7",
      "title": "Frameworks",
      "focus": "",
      "goal": "fluency in the tools that implement the patterns. Fix vocabulary first, then go deep on LangGraph (the one interviewers ask about most)",
      "sections": [
        {
          "id": "pillar-7",
          "title": "Core",
          "items": [
            {
              "id": "p7-langchain-vs-langgraph-vs-langsmith",
              "subtopic": "LangChain vs LangGraph vs LangSmith",
              "resourceName": "Stop Confusing LangChain/LangGraph/LangSmith - ByteMonk",
              "url": "https://www.youtube.com/watch?v=e-GR3PlEOVU",
              "urlType": "video",
              "lengthLabel": "12m",
              "lengthMinutes": 12,
              "isKey": true,
              "alt": {
                "deep": {
                  "resourceName": "Stop Confusing LangChain/LangGraph/LangSmith - ByteMonk",
                  "url": "https://www.youtube.com/watch?v=e-GR3PlEOVU",
                  "urlType": "video",
                  "lengthLabel": "12m",
                  "lengthMinutes": 12
                },
                "free": {
                  "resourceName": "Stop Confusing LangChain/LangGraph/LangSmith - ByteMonk",
                  "url": "https://www.youtube.com/watch?v=e-GR3PlEOVU",
                  "urlType": "video",
                  "lengthLabel": "12m",
                  "lengthMinutes": 12
                }
              }
            },
            {
              "id": "p7-langgraph-state-nodes-edges-memory-hitl",
              "subtopic": "LangGraph: state, nodes, edges, memory, HITL",
              "resourceName": "Krish Naik Bootcamp · free 10-hr",
              "url": "https://www.youtube.com/watch?v=rV3HJ4LEZ7k",
              "urlType": "video",
              "lengthLabel": "Udemy/11h",
              "lengthMinutes": 660,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "Krish Naik Bootcamp · free 10-hr",
                  "url": "https://www.youtube.com/watch?v=rV3HJ4LEZ7k",
                  "urlType": "video",
                  "lengthLabel": "Udemy/11h",
                  "lengthMinutes": 660
                },
                "free": {
                  "resourceName": "Krish Naik Bootcamp (free 10-hr) + 🟢 LangChain Academy - Intro to LangGraph (official, free)",
                  "url": null,
                  "urlType": "video",
                  "lengthLabel": "~11h + ~4h",
                  "lengthMinutes": 660
                }
              }
            },
            {
              "id": "p7-langgraph-full-free-course",
              "subtopic": "LangGraph full free course",
              "resourceName": "LangGraph complete course - freeCodeCamp",
              "url": "https://www.youtube.com/watch?v=jGg_1h0qzaM",
              "urlType": "video",
              "lengthLabel": "3h",
              "lengthMinutes": 180,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "LangGraph complete course - freeCodeCamp",
                  "url": "https://www.youtube.com/watch?v=jGg_1h0qzaM",
                  "urlType": "video",
                  "lengthLabel": "3h",
                  "lengthMinutes": 180
                },
                "free": {
                  "resourceName": "LangGraph complete course - freeCodeCamp",
                  "url": "https://www.youtube.com/watch?v=jGg_1h0qzaM",
                  "urlType": "video",
                  "lengthLabel": "3h",
                  "lengthMinutes": 180
                }
              }
            },
            {
              "id": "p7-crewai-openai-sdk-autogen-adk",
              "subtopic": "CrewAI / OpenAI SDK / AutoGen / ADK",
              "resourceName": "Ed Donner - Agentic AI Engineering (Wks 2-5)",
              "url": "https://github.com/ed-donner/agents",
              "urlType": "repo",
              "lengthLabel": "Udemy",
              "lengthMinutes": null,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "Ed Donner - Agentic AI Engineering (Wks 2-5)",
                  "url": "https://github.com/ed-donner/agents",
                  "urlType": "repo",
                  "lengthLabel": "Udemy",
                  "lengthMinutes": null
                }
              }
            },
            {
              "id": "p7-tracing-debugging-langsmith",
              "subtopic": "Tracing & debugging (LangSmith)",
              "resourceName": "LangSmith docs & walkthroughs",
              "url": "https://docs.langchain.com/langsmith/",
              "urlType": "doc",
              "lengthLabel": "docs",
              "lengthMinutes": null,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "LangSmith docs & walkthroughs",
                  "url": "https://docs.langchain.com/langsmith/",
                  "urlType": "doc",
                  "lengthLabel": "docs",
                  "lengthMinutes": null
                },
                "free": {
                  "resourceName": "LangSmith docs & walkthroughs",
                  "url": "https://docs.langchain.com/langsmith/",
                  "urlType": "doc",
                  "lengthLabel": "docs",
                  "lengthMinutes": null
                }
              }
            }
          ]
        }
      ],
      "callouts": [],
      "extras": {
        "free": [
          {
            "sectionTitle": "Extras",
            "items": [
              {
                "id": "f7-crewai-survey-only",
                "subtopic": "CrewAI (survey only)",
                "resourceName": "Multi AI Agent Systems with crewAI - DeepLearning.AI",
                "url": null,
                "urlType": "video",
                "lengthLabel": "~1.5h",
                "lengthMinutes": 90,
                "isKey": false
              },
              {
                "id": "f7-autogen-survey-only",
                "subtopic": "AutoGen (survey only)",
                "resourceName": "AI Agentic Design Patterns with AutoGen - DeepLearning.AI",
                "url": null,
                "urlType": "video",
                "lengthLabel": "~1.5h",
                "lengthMinutes": 90,
                "isKey": false
              },
              {
                "id": "f7-openai-agents-sdk-survey-only",
                "subtopic": "OpenAI Agents SDK (survey only)",
                "resourceName": "OpenAI Agents SDK - official docs & quickstart",
                "url": null,
                "urlType": "doc",
                "lengthLabel": "read",
                "lengthMinutes": null,
                "isKey": false
              }
            ]
          }
        ]
      }
    },
    {
      "number": 8,
      "slugId": "pillar-8",
      "title": "Model Context Protocol (MCP)",
      "focus": "",
      "goal": "understand, build, AND secure MCP. Intro videos cover why/architecture but skip client-side primitives and the entire MCP security attack class",
      "sections": [
        {
          "id": "pillar-8-8a-concepts-build",
          "title": "8a · Concepts & build",
          "items": [
            {
              "id": "p8-why-mcp-2-min-mental-model",
              "subtopic": "Why MCP (2-min mental model)",
              "resourceName": "How MCP actually works - Google Cloud Tech",
              "url": "https://www.youtube.com/watch?v=cGuyrANVi4A",
              "urlType": "video",
              "lengthLabel": "8m",
              "lengthMinutes": 8,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "How MCP actually works - Google Cloud Tech",
                  "url": "https://www.youtube.com/watch?v=cGuyrANVi4A",
                  "urlType": "video",
                  "lengthLabel": "8m",
                  "lengthMinutes": 8
                },
                "free": {
                  "resourceName": "How MCP actually works - Google Cloud Tech",
                  "url": "https://www.youtube.com/watch?v=cGuyrANVi4A",
                  "urlType": "video",
                  "lengthLabel": "8m",
                  "lengthMinutes": 8
                }
              }
            },
            {
              "id": "p8-why-architecture-lifecycle-build",
              "subtopic": "Why → Architecture → Lifecycle → Build",
              "resourceName": "MCP Trilogy playlist - CampusX",
              "url": "https://www.youtube.com/playlist?list=PLKnIA16_Rmva_oZ9F4ayUu9qcWgF7Fyc0",
              "urlType": "read",
              "lengthLabel": "8 vids",
              "lengthMinutes": null,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "MCP Trilogy playlist - CampusX",
                  "url": "https://www.youtube.com/playlist?list=PLKnIA16_Rmva_oZ9F4ayUu9qcWgF7Fyc0",
                  "urlType": "video",
                  "lengthLabel": "8 vids",
                  "lengthMinutes": null
                },
                "free": {
                  "resourceName": "MCP Trilogy playlist - CampusX",
                  "url": "https://www.youtube.com/playlist?list=PLKnIA16_Rmva_oZ9F4ayUu9qcWgF7Fyc0",
                  "urlType": "video",
                  "lengthLabel": "8 vids",
                  "lengthMinutes": null
                }
              }
            },
            {
              "id": "p8-full-build-server-client-tools-resources-prompts",
              "subtopic": "Full build: server+client, tools, resources, prompts, SAMPLING",
              "resourceName": "Ultimate MCP Crash Course - Web Dev Simplified",
              "url": "https://www.youtube.com/watch?v=ZoZxQwp1PiM",
              "urlType": "video",
              "lengthLabel": "1h15m",
              "lengthMinutes": 75,
              "isKey": true,
              "alt": {
                "deep": {
                  "resourceName": "Ultimate MCP Crash Course - Web Dev Simplified",
                  "url": "https://www.youtube.com/watch?v=ZoZxQwp1PiM",
                  "urlType": "video",
                  "lengthLabel": "1h15m",
                  "lengthMinutes": 75
                },
                "free": {
                  "resourceName": "Ultimate MCP Crash Course - Web Dev Simplified",
                  "url": "https://www.youtube.com/watch?v=ZoZxQwp1PiM",
                  "urlType": "video",
                  "lengthLabel": "1h15m",
                  "lengthMinutes": 75
                }
              }
            },
            {
              "id": "p8-production-server-w-fastmcp-auth",
              "subtopic": "Production server w/ FastMCP + auth",
              "resourceName": "Production-Ready MCP Server in 90 min - codebasics",
              "url": "https://www.youtube.com/watch?v=oG9yVmggMnE",
              "urlType": "video",
              "lengthLabel": "1h42m",
              "lengthMinutes": 102,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "Production-Ready MCP Server in 90 min - codebasics",
                  "url": "https://www.youtube.com/watch?v=oG9yVmggMnE",
                  "urlType": "video",
                  "lengthLabel": "1h42m",
                  "lengthMinutes": 102
                },
                "free": {
                  "resourceName": "Production-Ready MCP Server in 90 min - codebasics",
                  "url": "https://www.youtube.com/watch?v=oG9yVmggMnE",
                  "urlType": "video",
                  "lengthLabel": "1h42m",
                  "lengthMinutes": 102
                }
              }
            },
            {
              "id": "p8-hands-on-labs-multi-language",
              "subtopic": "Hands-on labs (multi-language)",
              "resourceName": "MCP for Beginners - Microsoft (GitHub)",
              "url": "https://github.com/microsoft/mcp-for-beginners",
              "urlType": "repo",
              "lengthLabel": "repo",
              "lengthMinutes": null,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "MCP for Beginners - Microsoft (GitHub)",
                  "url": "https://github.com/microsoft/mcp-for-beginners",
                  "urlType": "repo",
                  "lengthLabel": "repo",
                  "lengthMinutes": null
                },
                "free": {
                  "resourceName": "MCP for Beginners - Microsoft (GitHub, free repo)",
                  "url": null,
                  "urlType": "repo",
                  "lengthLabel": "repo",
                  "lengthMinutes": null
                }
              }
            },
            {
              "id": "p8-all-in-one-course-incl-security",
              "subtopic": "All-in-one course (incl. security)",
              "resourceName": "Eden Marco - MCP Crash Course *or* Nikolai Schuler - Complete MCP Developer Guide (OAuth 2.1)",
              "url": "https://www.udemy.com/course/model-context-protocol/",
              "urlType": "course",
              "lengthLabel": "Udemy",
              "lengthMinutes": null,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "Eden Marco - MCP Crash Course *or* Nikolai Schuler - Complete MCP Developer Guide (OAuth 2.1)",
                  "url": "https://www.udemy.com/course/model-context-protocol/",
                  "urlType": "course",
                  "lengthLabel": "Udemy",
                  "lengthMinutes": null
                }
              }
            }
          ]
        },
        {
          "id": "pillar-8-8b-mcp-security-the-gap-almost-everyone-misses-k",
          "title": "8b · MCP security (the gap almost everyone misses) [KEY]",
          "items": [
            {
              "id": "p8-tool-poisoning-line-jumping-rug-pulls",
              "subtopic": "Tool poisoning, line jumping, rug pulls",
              "resourceName": "MCP Tool Poisoning - OWASP Foundation",
              "url": "https://owasp.org/www-community/attacks/MCP_Tool_Poisoning",
              "urlType": "read",
              "lengthLabel": "read",
              "lengthMinutes": null,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "MCP Tool Poisoning - OWASP Foundation",
                  "url": "https://owasp.org/www-community/attacks/MCP_Tool_Poisoning",
                  "urlType": "read",
                  "lengthLabel": "read",
                  "lengthMinutes": null
                },
                "free": {
                  "resourceName": "MCP Tool Poisoning - OWASP Foundation",
                  "url": "https://owasp.org/www-community/attacks/MCP_Tool_Poisoning",
                  "urlType": "read",
                  "lengthLabel": "read",
                  "lengthMinutes": null
                }
              }
            },
            {
              "id": "p8-full-threat-model-defenses",
              "subtopic": "Full threat model + defenses",
              "resourceName": "MCP Security: Tool Poisoning threat model - Lens",
              "url": "https://lenshq.io/blog/mcp-security-tool-poisoning-threat-model/",
              "urlType": "read",
              "lengthLabel": "read",
              "lengthMinutes": null,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "MCP Security: Tool Poisoning threat model - Lens",
                  "url": "https://lenshq.io/blog/mcp-security-tool-poisoning-threat-model/",
                  "urlType": "read",
                  "lengthLabel": "read",
                  "lengthMinutes": null
                },
                "free": {
                  "resourceName": "MCP Security: Tool Poisoning threat model - Lens",
                  "url": "https://lenshq.io/blog/mcp-security-tool-poisoning-threat-model/",
                  "urlType": "read",
                  "lengthLabel": "read",
                  "lengthMinutes": null
                }
              }
            },
            {
              "id": "p8-auth-credential-risk-cves",
              "subtopic": "Auth, credential risk, CVEs",
              "resourceName": "MCP Security Complete Guide - SentinelOne",
              "url": "https://www.sentinelone.com/cybersecurity-101/cybersecurity/mcp-security/",
              "urlType": "read",
              "lengthLabel": "read",
              "lengthMinutes": null,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "MCP Security Complete Guide - SentinelOne",
                  "url": "https://www.sentinelone.com/cybersecurity-101/cybersecurity/mcp-security/",
                  "urlType": "read",
                  "lengthLabel": "read",
                  "lengthMinutes": null
                },
                "free": {
                  "resourceName": "MCP Security Complete Guide - SentinelOne",
                  "url": "https://www.sentinelone.com/cybersecurity-101/cybersecurity/mcp-security/",
                  "urlType": "read",
                  "lengthLabel": "read",
                  "lengthMinutes": null
                }
              }
            }
          ]
        }
      ],
      "callouts": [
        {
          "sectionId": "pillar-8-8b-mcp-security-the-gap-almost-everyone-misses-k",
          "text": "Gap fill - MCP security:: The MCP spec explicitly does NOT enforce security. A malicious server can hide instructions in tool descriptions/responses that your model trusts as developer instructions (tool poisoning) - a supply-chain-style attack, worse than normal prompt injection. Defenses: treat servers like pinned dependencies (version + content hash), default read-only, re-approve after changes, sandbox execution, validate tool responses before they hit the context."
        }
      ],
      "extras": {
        "free": [
          {
            "sectionTitle": "9a · Concepts & build",
            "items": [
              {
                "id": "f8-official-spec-mental-model",
                "subtopic": "Official spec & mental model",
                "resourceName": "modelcontextprotocol.io - official docs",
                "url": null,
                "urlType": "doc",
                "lengthLabel": "read",
                "lengthMinutes": null,
                "isKey": false
              }
            ]
          }
        ]
      }
    },
    {
      "number": 9,
      "slugId": "pillar-9",
      "title": "Evals & Observability",
      "focus": "",
      "goal": "stop guess-and-tweak. Evaluation-driven development is the single biggest predictor of agent-building success (per Andrew Ng)",
      "sections": [
        {
          "id": "pillar-9",
          "title": "Core",
          "items": [
            {
              "id": "p9-objective-vs-llm-judge-error-analysis-traces",
              "subtopic": "Objective vs LLM-judge; error analysis; traces",
              "resourceName": "Agentic AI - Module 4 (Andrew Ng)",
              "url": "https://www.deeplearning.ai/courses/agentic-ai/",
              "urlType": "read",
              "lengthLabel": "in course",
              "lengthMinutes": null,
              "isKey": true,
              "alt": {
                "deep": {
                  "resourceName": "Agentic AI - Module 4 (Andrew Ng)",
                  "url": "https://www.deeplearning.ai/courses/agentic-ai/",
                  "urlType": "video",
                  "lengthLabel": "in course",
                  "lengthMinutes": null
                },
                "free": {
                  "resourceName": "Agentic AI - Module 4 (Andrew Ng)",
                  "url": "https://www.deeplearning.ai/courses/agentic-ai/",
                  "urlType": "video",
                  "lengthLabel": "in course",
                  "lengthMinutes": null
                }
              }
            },
            {
              "id": "p9-rag-evals-ragas-faithfulness-precision-recall",
              "subtopic": "RAG evals (RAGAS): faithfulness, precision, recall",
              "resourceName": "RAG Evaluation, RAGAS explained - Logical Lenses",
              "url": "https://www.youtube.com/watch?v=7_LTU0LA374",
              "urlType": "video",
              "lengthLabel": "12m",
              "lengthMinutes": 12,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "RAG Evaluation, RAGAS explained - Logical Lenses",
                  "url": "https://www.youtube.com/watch?v=7_LTU0LA374",
                  "urlType": "video",
                  "lengthLabel": "12m",
                  "lengthMinutes": 12
                },
                "free": {
                  "resourceName": "RAG Evaluation, RAGAS explained - Logical Lenses",
                  "url": "https://www.youtube.com/watch?v=7_LTU0LA374",
                  "urlType": "video",
                  "lengthLabel": "12m",
                  "lengthMinutes": 12
                }
              }
            },
            {
              "id": "p9-ragas-in-code-run-in-ci",
              "subtopic": "RAGAS in code (run in CI)",
              "resourceName": "RAGAS Evaluation Tutorial (local, no API) - write-up",
              "url": "https://jheiduk.com/posts/ragas-evaluation-tutorial/",
              "urlType": "read",
              "lengthLabel": "read",
              "lengthMinutes": null,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "RAGAS Evaluation Tutorial (local, no API) - write-up",
                  "url": "https://jheiduk.com/posts/ragas-evaluation-tutorial/",
                  "urlType": "read",
                  "lengthLabel": "read",
                  "lengthMinutes": null
                },
                "free": {
                  "resourceName": "RAGAS Evaluation Tutorial (local, no API) - write-up",
                  "url": "https://jheiduk.com/posts/ragas-evaluation-tutorial/",
                  "urlType": "read",
                  "lengthLabel": "read",
                  "lengthMinutes": null
                }
              }
            },
            {
              "id": "p9-tracing-observability-in-practice",
              "subtopic": "Tracing/observability in practice",
              "resourceName": "LangSmith docs",
              "url": "https://docs.langchain.com/langsmith/",
              "urlType": "doc",
              "lengthLabel": "docs",
              "lengthMinutes": null,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "LangSmith docs",
                  "url": "https://docs.langchain.com/langsmith/",
                  "urlType": "doc",
                  "lengthLabel": "docs",
                  "lengthMinutes": null
                },
                "free": {
                  "resourceName": "LangSmith docs",
                  "url": "https://docs.langchain.com/langsmith/",
                  "urlType": "doc",
                  "lengthLabel": "docs",
                  "lengthMinutes": null
                }
              }
            }
          ]
        }
      ],
      "callouts": [
        {
          "sectionId": "pillar-9",
          "text": "Gap fill:: Traditional metrics (BLEU/ROUGE) don't work for RAG/agents - they measure wording, not grounding. Use RAGAS (no human labels needed) and treat it like unit tests in CI. For agents: prefer a rubric with a binary score per behavior over a vague 1-10 LLM-judge."
        }
      ],
      "extras": {
        "deep": [
          {
            "sectionTitle": "Extras",
            "items": [
              {
                "id": "d9-serving-an-llm-app-behind-an-api",
                "subtopic": "Serving an LLM app behind an API",
                "resourceName": "FastAPI + async streaming responses (SSE/WebSockets)",
                "url": null,
                "urlType": "video",
                "lengthLabel": "reuse your Node/React skills for the frontend",
                "lengthMinutes": null,
                "isKey": false
              },
              {
                "id": "d9-containerizing-ai-apps",
                "subtopic": "Containerizing AI apps",
                "resourceName": "Docker image with model deps, vector DB sidecar",
                "url": null,
                "urlType": "read",
                "lengthLabel": "you already know this - apply it",
                "lengthMinutes": null,
                "isKey": false
              },
              {
                "id": "d9-vector-db-hosting-choices",
                "subtopic": "Vector DB hosting choices",
                "resourceName": "Pinecone/Weaviate/pgvector/Qdrant - managed vs self-hosted",
                "url": null,
                "urlType": "video",
                "lengthLabel": "pick one, go deep",
                "lengthMinutes": null,
                "isKey": false
              },
              {
                "id": "d9-cost-latency-optimization",
                "subtopic": "Cost & latency optimization",
                "resourceName": "caching, prompt compression, batching, streaming-first UX",
                "url": null,
                "urlType": "video",
                "lengthLabel": "interview favorite topic",
                "lengthMinutes": null,
                "isKey": false
              },
              {
                "id": "d9-rate-limiting-retries-against-provider-apis",
                "subtopic": "Rate limiting & retries against provider APIs",
                "resourceName": "exponential backoff, fallback models",
                "url": null,
                "urlType": "video",
                "lengthLabel": "production reliability",
                "lengthMinutes": null,
                "isKey": false
              },
              {
                "id": "d9-ci-cd-for-ai-apps",
                "subtopic": "CI/CD for AI apps",
                "resourceName": "eval suite (RAGAS) gating deploys, not just unit tests",
                "url": null,
                "urlType": "video",
                "lengthLabel": "ties back to Phase 10",
                "lengthMinutes": null,
                "isKey": false
              },
              {
                "id": "d9-monitoring-in-production",
                "subtopic": "Monitoring in production",
                "resourceName": "token usage, latency, error rates, drift in eval scores",
                "url": null,
                "urlType": "video",
                "lengthLabel": "LangSmith / custom dashboards",
                "lengthMinutes": null,
                "isKey": false
              }
            ]
          }
        ],
        "free": [
          {
            "sectionTitle": "Extras",
            "items": [
              {
                "id": "f9-structured-eval-workflows-debugging",
                "subtopic": "Structured eval workflows, debugging",
                "resourceName": "Evaluating and Debugging Generative AI - DeepLearning.AI (W&B)",
                "url": null,
                "urlType": "video",
                "lengthLabel": "~1h",
                "lengthMinutes": 60,
                "isKey": false
              },
              {
                "id": "f9-serving-an-llm-app-behind-an-api",
                "subtopic": "Serving an LLM app behind an API",
                "resourceName": "FastAPI official tutorial (streaming/SSE section)",
                "url": null,
                "urlType": "video",
                "lengthLabel": "free docs",
                "lengthMinutes": null,
                "isKey": false
              },
              {
                "id": "f9-containerizing-ai-apps",
                "subtopic": "Containerizing AI apps",
                "resourceName": "Docker official docs - multi-stage builds",
                "url": null,
                "urlType": "doc",
                "lengthLabel": "reuse existing skill",
                "lengthMinutes": null,
                "isKey": false
              },
              {
                "id": "f9-vector-db-hosting-choices",
                "subtopic": "Vector DB hosting choices",
                "resourceName": "Qdrant/Weaviate/pgvector - official quickstart docs (all have free tiers)",
                "url": null,
                "urlType": "doc",
                "lengthLabel": "pick one, go deep",
                "lengthMinutes": null,
                "isKey": false
              },
              {
                "id": "f9-cost-latency-optimization",
                "subtopic": "Cost & latency optimization",
                "resourceName": "Provider docs on caching, batching, streaming (OpenAI/Anthropic docs)",
                "url": null,
                "urlType": "doc",
                "lengthLabel": "read",
                "lengthMinutes": null,
                "isKey": false
              },
              {
                "id": "f9-rate-limiting-retries",
                "subtopic": "Rate limiting & retries",
                "resourceName": "tenacity / backoff library docs (Python)",
                "url": null,
                "urlType": "doc",
                "lengthLabel": "code-along",
                "lengthMinutes": null,
                "isKey": false
              },
              {
                "id": "f9-ci-cd-gating-on-evals",
                "subtopic": "CI/CD gating on evals",
                "resourceName": "GitHub Actions docs + RAGAS-in-CI write-up (Phase 4c)",
                "url": null,
                "urlType": "repo",
                "lengthLabel": "free",
                "lengthMinutes": null,
                "isKey": false
              },
              {
                "id": "f9-monitoring-in-production",
                "subtopic": "Monitoring in production",
                "resourceName": "LangSmith docs (free tier) or open-source alternative (e.g. Langfuse self-hosted, free)",
                "url": null,
                "urlType": "doc",
                "lengthLabel": "free tier",
                "lengthMinutes": null,
                "isKey": false
              }
            ]
          }
        ]
      }
    },
    {
      "number": 10,
      "slugId": "pillar-10",
      "title": "Security (Full OWASP Top-10 for LLM)",
      "focus": "",
      "goal": "know all ten risks, not just prompt injection. This is the biggest single-video gap - one injection video leaves 9 risks uncovered",
      "sections": [
        {
          "id": "pillar-10",
          "title": "Core",
          "items": [
            {
              "id": "p10-all-10-risks-in-4-minutes-overview",
              "subtopic": "All 10 risks in 4 minutes (overview)",
              "resourceName": "OWASP Top-10 for LLM 2025, full overview - Giskard",
              "url": "https://www.youtube.com/watch?v=j04st4edDKI",
              "urlType": "video",
              "lengthLabel": "4m",
              "lengthMinutes": 4,
              "isKey": true,
              "alt": {
                "deep": {
                  "resourceName": "OWASP Top-10 for LLM 2025, full overview - Giskard",
                  "url": "https://www.youtube.com/watch?v=j04st4edDKI",
                  "urlType": "video",
                  "lengthLabel": "4m",
                  "lengthMinutes": 4
                },
                "free": {
                  "resourceName": "OWASP Top-10 for LLM 2025, full overview - Giskard",
                  "url": "https://www.youtube.com/watch?v=j04st4edDKI",
                  "urlType": "video",
                  "lengthLabel": "4m",
                  "lengthMinutes": 4
                }
              }
            },
            {
              "id": "p10-llm01-prompt-injection-direct-indirect",
              "subtopic": "LLM01 Prompt Injection (direct/indirect)",
              "resourceName": "OWASP LLM01 explained - IT Bulls",
              "url": "https://www.youtube.com/watch?v=IvDCxdJRKRg",
              "urlType": "video",
              "lengthLabel": "25m",
              "lengthMinutes": 25,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "OWASP LLM01 explained - IT Bulls",
                  "url": "https://www.youtube.com/watch?v=IvDCxdJRKRg",
                  "urlType": "video",
                  "lengthLabel": "25m",
                  "lengthMinutes": 25
                },
                "free": {
                  "resourceName": "OWASP LLM01 explained - IT Bulls",
                  "url": "https://www.youtube.com/watch?v=IvDCxdJRKRg",
                  "urlType": "video",
                  "lengthLabel": "25m",
                  "lengthMinutes": 25
                }
              }
            },
            {
              "id": "p10-deep-dive-w-real-exploits-fixes",
              "subtopic": "Deep dive w/ real exploits & fixes",
              "resourceName": "OWASP Top-10 for LLM deep dive - Ali Dorri",
              "url": "https://www.linkedin.com/posts/ali-dorri_deep-dive-into-owasp-top-10-for-large-language-activity-7336189972179230720-xkUX",
              "urlType": "read",
              "lengthLabel": "30m",
              "lengthMinutes": 30,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "OWASP Top-10 for LLM deep dive - Ali Dorri",
                  "url": "https://www.linkedin.com/posts/ali-dorri_deep-dive-into-owasp-top-10-for-large-language-activity-7336189972179230720-xkUX",
                  "urlType": "video",
                  "lengthLabel": "30m",
                  "lengthMinutes": 30
                },
                "free": {
                  "resourceName": "OWASP Top-10 for LLM deep dive - Ali Dorri",
                  "url": "https://www.linkedin.com/posts/ali-dorri_deep-dive-into-owasp-top-10-for-large-language-activity-7336189972179230720-xkUX",
                  "urlType": "video",
                  "lengthLabel": "30m",
                  "lengthMinutes": 30
                }
              }
            },
            {
              "id": "p10-practitioner-guide-every-entry-controls",
              "subtopic": "Practitioner guide (every entry + controls)",
              "resourceName": "OWASP Top-10 for LLM - Practical Guide",
              "url": "https://maciejzalwert.medium.com/securing-llm-systems-a-practical-guide-to-the-owasp-top-10-c95453611374",
              "urlType": "read",
              "lengthLabel": "18m read",
              "lengthMinutes": 18,
              "isKey": false,
              "alt": {
                "deep": {
                  "resourceName": "OWASP Top-10 for LLM - Practical Guide",
                  "url": "https://maciejzalwert.medium.com/securing-llm-systems-a-practical-guide-to-the-owasp-top-10-c95453611374",
                  "urlType": "read",
                  "lengthLabel": "18m read",
                  "lengthMinutes": 18
                },
                "free": {
                  "resourceName": "OWASP Top-10 for LLM - Practical Guide",
                  "url": "https://maciejzalwert.medium.com/securing-llm-systems-a-practical-guide-to-the-owasp-top-10-c95453611374",
                  "urlType": "read",
                  "lengthLabel": "18m read",
                  "lengthMinutes": 18
                }
              }
            },
            {
              "id": "p10-full-defensive-course",
              "subtopic": "Full defensive course",
              "resourceName": "OWASP Top 10 for LLM Applications: AI Security Explained",
              "url": "https://www.udemy.com/courses/search/?q=owasp+top+10+llm+applications",
              "urlType": "course",
              "lengthLabel": "Udemy 13h",
              "lengthMinutes": 780,
              "isKey": false
            }
          ]
        }
      ],
      "callouts": [
        {
          "sectionId": "pillar-10",
          "text": "The 10 risks you must be able to name (LLM01-LLM10):"
        }
      ]
    }
  ],
  "sequence": [
    {
      "weeks": "1-2",
      "focus": "Foundations",
      "resources": "Pillar 1 (transformers, 4 videos) + Pillar 2 start (Ed Donner Wks 1-2)",
      "isKey": false
    },
    {
      "weeks": "3-5",
      "focus": "RAG",
      "resources": "Pillar 3 all (build in Wk5) + Pillar 9 RAGAS",
      "isKey": true
    },
    {
      "weeks": "6",
      "focus": "Fine-tuning (optional)",
      "resources": "Pillar 4 - skim unless a role needs it",
      "isKey": false
    },
    {
      "weeks": "7-8",
      "focus": "Agents + Context",
      "resources": "Pillar 5 (Andrew Ng) + Pillar 6 (context/memory)",
      "isKey": false
    },
    {
      "weeks": "9-11",
      "focus": "Frameworks",
      "resources": "Pillar 7 - ByteMonk → LangGraph → multi-agent",
      "isKey": false
    },
    {
      "weeks": "12-13",
      "focus": "MCP + Security",
      "resources": "Pillar 8 (build + security) + Pillar 10 (OWASP Top-10)",
      "isKey": false
    },
    {
      "weeks": "14-17",
      "focus": "Build & Ship",
      "resources": "Ed Donner Agentic AI Engineering - deploy 2-3 projects",
      "isKey": false
    }
  ],
  "portfolio": [
    {
      "id": "rag-knowledge-worker-with-hybrid-search-",
      "title": "RAG knowledge-worker with hybrid search + reranking + RAGAS scores"
    },
    {
      "id": "multi-agent-langgraph-system-with-memory",
      "title": "Multi-agent LangGraph system with memory + tracing"
    },
    {
      "id": "mcp-powered-agent-with-a-secured-server",
      "title": "MCP-powered agent (with a secured server)"
    },
    {
      "id": "a-deployed-career-digital-twin",
      "title": "A deployed Career Digital Twin"
    }
  ],
  "deliverableBar": "Clean READMEs (problem → approach → results → next) + a 2-min demo each. Deployed, demoable projects beat any certificate.",
  "generatedAt": "2026-08-22T09:04:09.856Z"
};
