import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const partsDir = resolve(__dirname, "quiz-parts");
const OUT = resolve(__dirname, "../src/data/quizzes.ts");

interface Question {
  id: string;
  prompt: string;
  options: string[];
  answerIndex: number;
  explanation: string;
}
interface PillarQuiz {
  pillarN: number;
  questions: Question[];
}

const merged = new Map<number, PillarQuiz>();
for (const file of readdirSync(partsDir).filter((f) => f.endsWith(".json")).sort()) {
  const part: PillarQuiz[] = JSON.parse(readFileSync(resolve(partsDir, file), "utf-8"));
  for (const pq of part) {
    const existing = merged.get(pq.pillarN);
    if (existing) {
      existing.questions.push(...pq.questions);
      existing.questions.sort(
        (x, y) => parseInt(x.id.split("-q")[1], 10) - parseInt(y.id.split("-q")[1], 10)
      );
    } else {
      merged.set(pq.pillarN, { pillarN: pq.pillarN, questions: [...pq.questions] });
    }
  }
}

const quizzes = [...merged.values()].sort((a, b) => a.pillarN - b.pillarN);

const ids = new Set<string>();
for (const q of quizzes) {
  if (q.questions.length !== 8)
    throw new Error(`Pillar ${q.pillarN}: expected 8 questions, got ${q.questions.length}`);
  for (const item of q.questions) {
    if (ids.has(item.id)) throw new Error(`Duplicate question id ${item.id}`);
    ids.add(item.id);
    if (item.options.length !== 4) throw new Error(`${item.id}: needs 4 options`);
    if (item.answerIndex < 0 || item.answerIndex > 3) throw new Error(`${item.id}: bad answerIndex`);
    if (!item.explanation || !item.prompt) throw new Error(`${item.id}: empty fields`);
  }
}
if (quizzes.length !== 10) throw new Error(`Expected 10 pillar quizzes, got ${quizzes.length}`);

const banner = `// AUTO-GENERATED by scripts/build-quizzes.ts — do not edit by hand.
export interface QuizQuestion {
  id: string;
  prompt: string;
  options: string[];
  answerIndex: number;
  explanation: string;
}
export interface PillarQuiz {
  pillarN: number;
  questions: QuizQuestion[];
}

export const QUIZZES: PillarQuiz[] = ${JSON.stringify(quizzes, null, 1)};
`;

writeFileSync(OUT, banner, "utf-8");
console.log(`quizzes=${quizzes.length} questions=${ids.size} -> wrote ${OUT}`);
